### ISSUE TITLE
Add 2+ new columns sequentially in the middle of the table

### ISSUE THREAD

**Issue by aik099** [TablePlus/TablePlus#1001]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

195

3. The steps to reproduce this issue:

Right now it's possible to add new column after existing column by specifying desired order in `#` column in structure view. Unfortunately the specified number is only valid for existing columns and not columns, that are in green color (added, but changes not saved to database).

**Comment by huyphams** [comment]
Hi @aik099 this is reported multiple times. please keep calm and wait until it is implemented! we have a few people subscribe to this channel, it could spam their inbox email and it's really hard for me to track the issues. (I have nearly 350 issues now).
 
Please also be consider to email me (huy@tableplusapp.com) if the suggestion is changing the current behavior because it can have a reason.

I highly appreciate your feedback because you're really involved in the product very seriously. Thank you so much!

**Comment by aik099** [comment]
I'm sorry. I thought this was a completely different scenario from one I've previously reported and that's why I've added another issue.

I'll try not to post issues related to position of added columns until feature is actually released.

**Comment by huyphams** [comment]
now, we can specify the # when creating a new columns, Thanks!
