### ISSUE TITLE
Cassandra filters not working

### ISSUE THREAD

**Issue by bartelsdan** [TablePlus/TablePlus#1066]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Cassandra 3.11

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Windows V1.0 (62)

3. The steps to reproduce this issue:
open a cassandra table
try to filter anything
doesn't work

to run via SQL query 'ALLOW FILTERING' needs to be added to the query.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by tryk** [comment]
"ALLOW FILTERING" checkbox would be very nice to see in Filters tab

**Comment by zhaoxiang0531** [comment]
I am facing the same issue. 
I totally agree to ask TablePlus product team to add a checkbox for "ALLOW FILTERING" in Filters tab. 
In some cases, the current feature is difficult to use.

**Comment by huyphams** [comment]
hey guys, I made a workaround solution for this case. TablePlus will confirm you to ALLOW FILTERING if you get this error.
<img width="1452" alt="Screen Shot 2019-07-25 at 11 01 08 PM" src="https://user-images.githubusercontent.com/3654622/61920548-5623f980-af30-11e9-864f-6d9891e43645.png">
The reason I don't want a dedicated option because people might forget it, and it can lead to performance issues.
Download: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
