### ISSUE TITLE
Strange bug after out of memory

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#107]
I received an OOM error on my comp, after which TablePlus application did not start up ever again, I had to download new version of TP to fix this.

I'm hoping the error reports were sent in properly.  sorry for brevity; recently injured my hand

**Comment by huyphams** [comment]
Hi @brian-crane, I hope you are well.

Thank you for the feedback. I will investigate on this issue and keep you posted. Currently I'm focusing to improve stability and performance of TablePlus by fixing crash bugs, unit test and memory optimization. TablePlus should handle large data set better.

Huy.

**Comment by brian-crane** [comment]
Thank you Huy; by the way TablePlus is becoming more powerful and stable with each release, today I could run a 390k line query, which before would have given me issues! :)

One request I have is for when viewing large queries from the History, it can take a few minutes to display the full 390k line query, you see the scrollbar moving up as it loads; maybe we can have a progress bar or something to let me know when my query is fully loaded from my history.

**Comment by huyphams** [comment]
Hi @brian-crane 
That is one of my goal to optimize SQL Query, you can see TablePlus can load a millions of line and hundred millions characters.

Currently, I can parse and detect syntax `hundred millions characters` less than 1 seconds. but the bottle neck is Apple Cocoa Framework, (that's why you can see the text is all black, because I disabled syntax high light temporary).

I'm trying to improve Cocoa Framework and added more feature into SQL Query (multi cursors, auto detect command under cursor etc...).
I will keep you posted.

Huy.
