### ISSUE TITLE
Sort is wrong when handling international characters (Å)

### ISSUE THREAD

**Issue by LETZSUSHI** [TablePlus/TablePlus#1089]
In Danish we have 3 extra characters: æ, ø and å. They're at the end of the alphabet (…u v w x y z æ ø å) When sorting "å" comes at the beginning, not the end.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 2.2 (212)

3. The steps to reproduce this issue: Open a table, sort on a column (with an entry that starts with å). 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @LETZSUSHI there are two types or sorting in TablePlus.

1. If you click the column header in the item (table, view) data it will send the query to the server. We can't do anything about this case because the sort is handled in the database server.

2. Sorting result. after running a query in Query Editor, click on the header to sort to result or sort column in the table structure => this sort is handled by TablePlus.

Which one is yours? Thanks
