### ISSUE TITLE
No option to add credentials for Mongo Connection

### ISSUE THREAD

**Issue by tapankavasthi** [TablePlus/TablePlus#1091]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Mongo DB (any version)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 215

3. The steps to reproduce this issue:
Create a new connection for Mongo. Option to add credentials for database not available in the dialog box.

<Details>
<Summary> See Snapshot </Summary>
<p>
<img width="502" alt="Screenshot 2019-04-05 at 1 08 54 PM" src="https://user-images.githubusercontent.com/38013895/55611841-5d1dd500-57a4-11e9-9723-2d170ccf6eb2.png">
</p>
</Details>

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @tapankavasthi you can include the password into the connection string:
see: https://docs.mongodb.com/manual/reference/connection-string/

**Comment by tapankavasthi** [comment]
<img width="504" alt="Screenshot 2019-04-05 at 4 35 00 PM" src="https://user-images.githubusercontent.com/38013895/55623514-da574300-57c0-11e9-86ff-7ff96d81af16.png">
^ It says invalid input.
My connection string is in the format:
mongodb://`user_name`:`password`@`ip`:`port`/`database`
Still unable to login.

**Comment by tapankavasthi** [comment]
<img width="486" alt="Screenshot 2019-04-05 at 4 48 23 PM" src="https://user-images.githubusercontent.com/38013895/55624167-bc8add80-57c2-11e9-861f-2bd89d9d623c.png">
^ Just as a try, I used the below link to encode my password for special characters. But it is giving above error.

**Comment by huyphams** [comment]
Hi @tapankavasthi I just tested with a mongo URL for both cases: directly and over SSH and it works fine.
I don't think that encode base 64 will work, you should follow the official document, they've mentioned how to encode the password.
Sorry because of the late response, I need to test it.
<img width="791" alt="Screen Shot 2019-04-05 at 8 04 12 PM" src="https://user-images.githubusercontent.com/3654622/55629689-00d7a700-57de-11e9-81fb-5f4e0a9a0ac7.png">

**Comment by zhangcunxiang** [comment]
But TablePlus can not connect to AWS DocumentDb with ssl=true and validate with rds-combined-ca-bundle.pem cert file

**Comment by ryan-idea42** [comment]
Yes... We need more options to connect with MongoDB. Like @zhangcunxiang mentioned, we use DocumentDB and I would LOVE to use TablePlus with it, but as it stands now, we can't connect because it requires certificate validation for something we don't have. 

I'm having to use another tool for now to connect with DocumentDB that takes in user name, password, and the certificate file from Amazon to get in. TablePlus is now just being used to access my local environment.

**Comment by Pouzor** [comment]
Do we have more information if this feature will come later? I like the way to connect to rds threw bastion and I hope I can do the same with document-db
