### ISSUE TITLE
A suggestion: Keep the case of tables as listed in "show tables" command

### ISSUE THREAD

**Issue by yuqiang-yuan** [TablePlus/TablePlus#1099]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL Server 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 212

3. The steps to reproduce this issue:

I used to use all uppercase characters in table name and column name, and I'd like the table names in the left tree keep the same as `show tables` command. like the attached image:

![image](https://user-images.githubusercontent.com/15667885/55954797-3d9a1700-5c92-11e9-9820-a95e9a666b51.png)

Thanks in advance if you could take into account this feature  in future releases.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
hi @yuqiang-yuan TablePlus doesn't use the `show tables;` to get the list of items on the left sidebar because there is no way to detect the item type (table or view).

We use this statement: `SELECT table_name as table_name,table_schema as table_schema,table_type as table_type FROM information_schema.tables WHERE table_schema = 'database_name';`

it seems that MySQL returns two different result set.

**Comment by yuqiang-yuan** [comment]
OK, I see, thank you very much.
