### ISSUE TITLE
Custom field support - Markdown, image, selectbox etc.

### ISSUE THREAD

**Issue by jenstornell** [TablePlus/TablePlus#1218]
I like this thing but I've search the internet for this, but with custom field support. With that I mean to edit the cells in another way.

- Date/time-picker for date/time fields
- Markdown for large text fields
- Selectbox for predefined options
- Image selector

To make it possible a blueprint of some kind would be needed which tells the app which type should apply to what column.

In the meantime I'm building my own thing, but I hope I don't need to spend that time.

**Comment by huyphams** [comment]
Hey @jenstornell because you’re not answer the template issue question, so i don’t know which is the platform/build you’re using. The macOS version supported all those feature a year ago

**Comment by jenstornell** [comment]
@huyphams Oh, I missed that important step. I tried 1.0 (70) on Windows. I guess Windows are a a few years behind the Mac version then?

I tried to find any screenshots of how it looks on a Mac on the website, but could not find it. Maybe it's "hidden" in a blog post somewhere? If there is such a feature, I think you would benefit to promote it more?

**Comment by huyphams** [comment]
Yep, the Windows version is just released recently, and here is the Windows issue repo:https://github.com/TablePlus/TablePlus-Windows/issues
The macOS supported all those features and also supported JSON Editor, view image, PDF and many more features... We're porting it to the Windows platform. I will close this issue because we're working on it, and also it's not related to the macOS issue repo. Thank you and have a great day!
<img width="312" alt="Screen Shot 2019-05-31 at 1 27 31 PM" src="https://user-images.githubusercontent.com/3654622/58686090-fc77d680-83a7-11e9-9a94-987b8cbe31ab.png">
<img width="973" alt="Screen Shot 2019-05-31 at 1 30 01 PM" src="https://user-images.githubusercontent.com/3654622/58686158-3c3ebe00-83a8-11e9-8e30-b372b3a953c2.png">

**Comment by robertmylne** [comment]
Still not added to Window 3 years on, please add to Windows. Testing this and trying to justify switching from PHPMyAdmin and this is a real killer not having.
