### ISSUE TITLE
Feedback for tableplus

### ISSUE THREAD

**Issue by nutmix** [TablePlus/TablePlus#1240]
I have been using heidisql for mysql, mysql workbench and toad for oracle for many years (20+)

Recently, I was required to switch to mac for work.

Finding something as good as heidisql for mac has proven difficult.

In evaluating your product, from first impression I have the following feedback:

1) when you open a connection to a database, you should show a list of databases.  Currently,it shows a blank ui, and you have to hunt for a way to get the list of databases, especially if you never use keyboard shortcuts.

2)  I see you have a tab for data and a tab for structure, but they are at the bottom, not the top.  I had to search for them. I would suggest moving them to a more logical place (i.e. the top, as tabs, like both toad and heidisql)

3) Heidisql and toad have the option to open a window where you can type in sql, and run it as a script or run a section. I cant find this feature on tableplus. I am sure its there, but the UI is not intuitive like heidisql. You could do a lot worse than copying them for things like this. I expected it to be next to data and structure "tabs". I still have not found this feature, so cant evaluate the sql editor.

4) there are no tool tips. There are icons, e.g. the "database" and a square one next to it, i the top left.  I don't know what these are by looking at them, and there is no tooltip to explain (on mac at least). Also at the very top left is an eye etc. Clicking on the eye (and the thing to the right of it) does nothing, and because there is no tooltip, I don't know what this is for. I recommend adding tooltips.

5) there is no user manual. E.g. I see you have a favourites button, and when i right click as instructed it opens an editor, but I have no idea what this is for.  I guessed it was to mark certina tables as favourites or similar. I am guessing you use it to store sql snippets, but then it should perhaps not be called favourites, it should be called snippets or maybe just SQL. Anyway, a user guide would clarify what its for.

6) I could not figure out how to save or view indexes.  I could not find anywhere how to view existing indexes on a table. I tried the "+ index" button, which opens a dialog on the right for entering the index name etc. But there is no "save" or "OK" button.  The table is now highlighted yellow on the left,but I dont know what that means. Again, as there is no help or user guide, I cant look this up.  For viewing and adding indexes, I would need to use another program (such as mysqlwordbench)

7) there is nowhere to view or add constraints.

OK, by accident I just found out there are tooltips, but the delay was too long. I.e. I was hovering, but nothing was poping up. I just hovered for a longer time, and now see the tooltips. So Now I can start tying to figure out the answers to some of the above UI issues.

8) Consider making the icons more obvious.  Now I found tooltips, I see that the "paragraph" symbol in the top left is in fact, the commit button I was looking for. A better icon would be a green tick, or a green "play" triangle. This is more universal.  The "rollback" button looks like a window close button.  Better might be to make it a red cross, or a red triangle pointing left.

What would really help is a simple annotated diagram of the UI, with arrows showing what the various buttons do.  I looked for this on the website also, but could not find anything.

Anyway, tableplus looks promising.

**Comment by huyphams** [comment]
Hey @nutmix we have a getting started at the bottom page: https://tableplus.com/blog/2018/04/getting-started-with-tableplus.html it’s the best way to getting started with TablePlus

**Comment by huyphams** [comment]
1. Actually, we want user know the database button on the top left and the shortcut key, that's why we don't show the database list.
2. You can move by shortcut key (in the preferences), or right click -> open structure.
3. You can open the editor by clicking the SQL button on the top left or pressing command + return or command + E.
4. All the icon and button have tooltip. but I guess Microsoft Windows shows it earlier than the macOS so you can't see it. The tooltip contains the shortcut key and button function. We can't change the tooltip delay because it's macOS standard.
5. I've mentioned the manual above.
6. TablePlus will pending all the changes until you commit, you can do it by clicking the button on the top left or just press command +S.
7. In the table structure.
...
I appreciate your feedback it would be easier to keep track the other issues (and also avoid spam 35 users who subscribe this repo) please kindly email me at nick@tableplus.com the repo only for bug/feature suggestion. Again, thank you so much for taking the time to try the app and give very long feedback.
Have a nice weekend.

**Comment by huyphams** [comment]
Follow via email.
