### ISSUE TITLE
SQL query fails to run when highlighting text in editor

### ISSUE THREAD

**Issue by majd** [TablePlus/TablePlus#1325]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL 9.6.13.

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 246.

3. The steps to reproduce this issue:

- Execute custom SQL query in SQL editor: Works fine. ✅
- Highlight a part of the query in editor the run the query: Fails. 🛑

<img width="972" alt="Screenshot 2019-07-24 at 13 52 49" src="https://user-images.githubusercontent.com/1644696/61791632-da845880-ae1a-11e9-875d-8ae0bc6cf2af.png">
 
<img width="971" alt="Screenshot 2019-07-24 at 13 53 00" src="https://user-images.githubusercontent.com/1644696/61791661-e708b100-ae1a-11e9-8c45-145cb0306554.png">

**Comment by huyphams** [comment]
Hi @majd this is expected behavior, TablePlus will execute the query under cursor or `selected text`, by doing this way, the user can easily execute the command they want to execute.
Imaging, if we remove this behavior, it would not possible to run execute this one:

select * from comments where id in (select comment_id in comment_from_users);

The user wants to highlight and execute the `select comment_id in comment_from_users`
