### ISSUE TITLE
Copy / Paste Row feature

### ISSUE THREAD

**Issue by silverbux** [TablePlus/TablePlus#1355]
Thanks for the copy/paste row feature it is helpful and i use it all the time, but the thing is it also copy primary auto increment column/field it would be awesome to keep that blank or auto fill the field as well so you wont have to manually enter incremental values

**Comment by huyphams** [comment]
Hi @silverbux thanks for the feedback. If you use the Duplicated feature, TablePlus will not fill the primary auto-increment value. (Select rows and then press command + D).

The reason we fill the value when copy/paste because the user may copy it from a database to a database and they want to keep the primary value (let's say that 50% users want to keep that values). At this point, TablePlus will not know if the IDs exist or not so it keeps the values.

If you duplicate rows from a table, TablePlus knows that the ID can be the same so it's safe to clean it up.

**Comment by silverbux** [comment]
nicee command + D will work for me, im was not aware of the feature. Thanks again @huyphams

**Comment by gylippus** [comment]
@silverbux once you duplicate them and the id is empty, is there a way to auto-create these incrementally higher than the last id present?
