### ISSUE TITLE
TablePlus forgets the license registration key when having it registered for multiple macOS users

### ISSUE THREAD

**Issue by roennie91** [TablePlus/TablePlus#1361]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Not applicable

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build: 252 (macOS Mojave 10,14,5)

3. The steps to reproduce this issue:
- Go to System Preferences > Users & Groups and create another Admin user, having access to TablePlus. Let's call them "Work" and let's call the current user you're logged in with, "Private".
- Then, open TablePlus, go to Register License, fill in your license key and click Activate.
- Close TablePlus, login with the newly created "Work" user and follow the steps to register a license.
- Logout, and log back in with the already registered "Private" user.
- Open TablePlus and you'll notice that it has forgotten the license key.
- Reactivating is indeed possible.

Noted: If the bug is related to data, please attach an example SQL data.
- I have two separate license keys, so my "Work" users uses a different key than my "Private" user.

**Comment by huyphams** [comment]
Hi, if you're using the same computer but different users, please copy the activated license key at 
`cp ~/Library/Application\ Support/com.tinyapp.TablePlus/.licensemac` to the new user.
Do not activate it with the same license because it will deactivate the old license file.
Please reach the support team via nick@tableplus.com if you're still seeing it.
Thank you!
