### ISSUE TITLE
[Feature Request] Update detail pane when changing table selection.

### ISSUE THREAD

**Issue by mikebronner** [TablePlus/TablePlus#138]
When changing the selected table with arrow keys on mac, the detail pane does not update to reflect the currently highlighted table.

This would be handy for traversing many tables quickly.

Thank you!

**Comment by huyphams** [comment]
@mikebronner TabePlus used to have this feature, but currently I changed the UX, because sometime we want to select multple table (for export, delete etc...) so I changed the UX to select then hit `return` to open table.

I just realize that we can archive both cases by detect user holding `shift` key. I will fix it on next update, thanks 👍

**Comment by mikebronner** [comment]
@huyphams awesome, thanks! :)

**Comment by mikebronner** [comment]
Yea, SHIFT-click, CMD-A, and CMD-click should probably be used to select multiple tables, along with SHIFT-↓ or SHIFT-↑. :)

**Comment by huyphams** [comment]
I fixed on new build 77, I will release it soon 💃

**Comment by huyphams** [comment]
Please check out new build 77 😄

**Comment by mikebronner** [comment]
@huyphams So sweet! confirmed working, thanks a bunch for the super-quick turn-around. :)
