### ISSUE TITLE
Feature Request: Add shortcut to show/hide query results pane

### ISSUE THREAD

**Issue by jim256** [TablePlus/TablePlus#1393]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Snowflake

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
256

3. The steps to reproduce this issue:
Feature request

It would be very handy to have a keyboard shortcut to toggle the query results window

**Comment by jim256** [comment]
Glad to hear it!

Sorry, can you please explain more about that tip? Which button are you referring to?

**Comment by vbalazs** [comment]
I think this has been added, as cmd+` but that's an unfortunate choice because it conflicts with the _move focus to the next window_ in case you have multiple windows open from the same application (eg.: when I work with two tableplus windows of two databases).

I think this is a standard macOS shortcut but I might be wrong.

In any case, I don't understand why some shortcuts can be changed/removed vs while some cannot, like this one.

**Comment by huyphams** [comment]
we've changed it to control + ` @vbalazs if you have a chance, you can download the patch here: https://www.dropbox.com/s/3rkgc4yylrr9buj/TablePlus.dmg?dl=0
We will add more custom shortcut in the next update.
Thanks.
