### ISSUE TITLE
Nullable decimal data type field throws errors when value is emptied

### ISSUE THREAD

**Issue by Chinese1904** [TablePlus/TablePlus#152]
Hi there,

I have a nullable decimal field that when I try to empty the value it throws this error:

<img width="424" alt="screen shot 2017-12-19 at 9 11 55 pm" src="https://user-images.githubusercontent.com/6228425/34192274-de046e3e-e501-11e7-825e-831ab675a856.png">

The query would be:
```sql
UPDATE `ordering`.`users` SET `lat` = '' WHERE `id` = '1';
```
It's supposed to just clear the value.

Thanks so much :-)

**Comment by huyphams** [comment]
The `empty` state means `empty` string, you can't set empty for numeric. There is `null option` when you hold option + click on the cell.

**Comment by Chinese1904** [comment]
Sorry, what I then meant is that when you clear the value, it should set it to null automatically instead. That's how SequelPro handles it as well

**Comment by huyphams** [comment]
Sequel Pro handle this case by automatic convert empty to NULL, but when I work with the database, I always respect user input. because if you do something implicitly and you didn't aware that TablePlus convert it automatically, it would be bad and dangerous somehow.

Some driver (Ex: SQLite), you can set empty for numeric. Convert automatically, in this case, it was wrong.

Btw, would be nice if we have a popup suggest user use option+click to select null if they tried to empty numeric.

**Comment by Chinese1904** [comment]
I like the idea of it being an option in settings to automatically convert empty to NULL and to have it automatically disabled, so users know the risk they could run into before they change it.
