### ISSUE TITLE
Feature Request: Auto toggle Quick Look Editor on text

### ISSUE THREAD

**Issue by miagg** [TablePlus/TablePlus#1529]
Quick Look Editor should be toggled automatically when we focus on a text field just like Sequel Pro does or at least provide an option.
A custom shortcut is also a welcome change.

**Comment by huyphams** [comment]
I'm not sure if I understand you correctly. but I've brought back the default tooltip macOS, The Quick Look in TablePlus is a different controller, you can trigger quick look with middle mouse.

<img width="924" alt="Screen Shot 2019-11-04 at 10 09 34 AM" src="https://user-images.githubusercontent.com/3654622/68126978-4c287400-feeb-11e9-9f80-ffa722d0cf53.png">

**Comment by adamwinn** [comment]
Is there any way to disable the Default tooltip (hover mouse)?  It's kind of unnecessary when you have the row detail pane open

**Comment by justin-schroeder** [comment]
I've been wondering about the OPs question too (I realize this isn't a support forum...but this ticket isn't closed so here goes nothing 🤷‍♂️): If I have a column of text, or json that's quite long, and a double click on that column, my preference would be for it to automatically open with the "Quick Look Editor" rather than in that tiny little scrollable text area.

![little-editor](https://user-images.githubusercontent.com/1950463/74756300-56744100-5242-11ea-83b8-9358a8b279cc.png)
![quicklook-editor](https://user-images.githubusercontent.com/1950463/74756301-56744100-5242-11ea-84fa-017c620c60de.png)

**Comment by huyphams** [comment]
Auto trigger Quicklook would break the behavior: edit -> tab -> paste or click -> select all -> paste for many users, who don't want to leave the keyboard.
If you view it on the right sidebar or using the middle mouse.
I'm closing this issue because it was supported in the recent build, if you want to suggest a new feature, feel free to open a new issue.

**Comment by huyphams** [comment]
Hi, you can open Quicklook quickly with command + enter from this build: https://www.dropbox.com/s/1m4ro31q15kcgnj/TablePlus.dmg?dl=0

**Comment by modernben** [comment]
I would still like to see this as the default. A double click on a JSON or TEXT field should open the modal just as it does in Sequel Pro/Sequel Ace.

**Comment by huyphams** [comment]
We believe that many people like the inline edit more than the popup (by default), there are many usecases:
1. double click to copy.
2. Double click to paste
3. Double click and delete all value (TablePlus will convert it to null as json don't have empty value)
4. Double click to start edit and press tab.
5. Double click view json.
6. Double click to edit large json.

Only 6 and 7 where the popup is helpful, the others are not. So it depends on your usecase. We have the cmd + enter/middle mouse to toggle the popup and we think it is fast enough when compared with double click
