### ISSUE TITLE
Delete/Paste/Duplicate buttons in context menu of query results

### ISSUE THREAD

**Issue by hyperknot** [TablePlus/TablePlus#1540]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): -

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
272

3. The steps to reproduce this issue:

    1\. Run any query, like a simple select
    2\. In the results, right click on any row
    3\. The context menu will offer choices like Delete/Paste/Duplicate which make no sense on a read-only data.

**Comment by huyphams** [comment]
Hi @hyperknot actually, they have actions, the reason I always put them there not only for the editable queries because I want the user to know that it's possible for some queries, and also keep the menu position consistent (if you know the menu position you can select the item without reading the titles).

![2019-11-07 00 07 05](https://user-images.githubusercontent.com/3654622/68359614-e3134d00-00f2-11ea-8a55-0006ca95b6fd.gif)
