### ISSUE TITLE
Feature Request: Keep tables Alphabetical after Search

### ISSUE THREAD

**Issue by nawlbergs** [TablePlus/TablePlus#1564]
MySql - TablePluss 2.11.2

Im coming over from Sequel Pro because its no longer maintained.. They have a great UI...

That said, one thing that is super annoying coming from Sequel Pro is that when I do a search for a table in TablePlus... the result ordering is all scrambled... I understand its trying to return them in a `google-like` smart fashion of what matched the most... but when I type `user` into the search... it actually makes finding the table I want much harder if I have 10 tables with the word `user` in it... 

Im requesting the search act more like a filter - which just returns the results in alphabetical order (or a setting to allow it to return that way.)

**Comment by lfolco** [comment]
Please please fix this. The current sort order makes no sense.

**Comment by keithslater** [comment]
I brought this up a long time ago and he made a build for us to test that did this, which is obviously outdated now. Perhaps this could be added as an option? It's the only thing that really drives me crazy about TablePlus.

From what I can tell, the results aren't scrambled, they're in order by the length of the table name then alphabetical (which is strange). You can see it better if you have a lot of tables that start the same:
![image](https://user-images.githubusercontent.com/940991/96882636-215d6580-1445-11eb-862a-ef010c3034f7.png)

I do think beyond starting with the same word, it does try to return results in order of some scoring system, not sure. But what I would like is if it all starts with the same characters, it should at least sort alpha instead of the length of the table name.

**Comment by huyphams** [comment]
Hey @keithslater please try to input the ^project
TablePlus does support regex so there are a lot of hidden option:

- Default: fuzzy
- "keyword" : search with contains (double quote the keyword)
- ^prefix
- suffix$

A|B : A or B

**Comment by huyphams** [comment]
I think we can close this issue because the ^prefix solved it! Thanks all.

**Comment by nawlbergs** [comment]
Yea.. I don't know that having users type regex is a good fix for what, in my mind, should be a default.
Also, most users probably don't know that regex is an option... then will have to to google search or come to this issue to find a solution.

**Comment by huyphams** [comment]
Sure thanks, we should make an in-app tutorial here (for the first time user click on the search field, TablePlus will show that popup). and maybe an option to change the default search behavior.

**Comment by nawlbergs** [comment]
its the regex mac only? - i just tried on the windows build with no luck.

**Comment by huyphams** [comment]
We will support it in the next update (if you want, we can send you the hotpatch).

**Comment by zdkroot** [comment]
Just coming here to say that after four years this is still a terrible solution. So literally 100% of my searches now need to start with ^, because why would I want anything else? Alphabetical should be the default return order after a search. Why am I here reading this thread at all? Because the current default behavior makes no sense and I had to search for a fix. How would I even know the search bar is regex enabled? That should be a button or toggle, and certainly not the default. Even my text text editor has such a button.

Very frustrating UI decision.

**Comment by zdkroot** [comment]
Awesome, this works, thank you @keithslater. I still dunno why this isn't the default, but whatever. This is fine.
