### ISSUE TITLE
Linux roadmap

### ISSUE THREAD

**Issue by rogierverbrugge** [TablePlus/TablePlus#1595]
@huyphams thanks for the linux alpha and the hard work. It basic but it works and I can check data so thats a plus. Do you guys have a roadmap with expected features?

For me the ability to write queries (not even code completion) and the ability to export the queried data into csv or memory would make it for me a all useable app. i can use the cli to manage users for now.

**Comment by huyphams** [comment]
It's supported @rogierverbrugge you can open a query editor by pressing control + T
![Screen Shot 2019-12-09 at 8 45 55 AM](https://user-images.githubusercontent.com/3654622/70436739-5eed1600-1a60-11ea-9a09-d8c408fdd711.png)

I'm closing this issue for now because we have another repo for Linux: https://github.com/TablePlus/TablePlus-Linux
