### ISSUE TITLE
Request: Automatically reconnect

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [TablePlus/TablePlus#1613]
Please can we have an option to have TablePlus automatically reconnect? Is there ever a moment where I wouldn't want that?

<img width="467" alt="Screenshot 2019-12-16 at 13 55 49" src="https://user-images.githubusercontent.com/6763222/70913665-62f3d780-200e-11ea-9117-646adb8a23d0.png">

**Comment by huyphams** [comment]
TablePlus will reconnect automatically 1 time, but not retry repeatedly if it fails.  You can reconnect by using the shortcut key Command + Shift + R

TablePlus used to have the feature that reconnects automatically but I've removed it due to many user requests (via email). The current behavior is the final decision because it rarely receives email support.

**Comment by huyphams** [comment]
The reason our users don't want that feature is simple. They leave TablePlus open over the night or all the time, and reconnect repeatedly is not a good idea.

**Comment by huyphams** [comment]
Hey @JohnnyWalkerDesign if you have any suggestion or question, feel free to email us at nick@tableplus.com there are 41 people who subscribe this repo and I don't want to spam their inbox 😛

**Comment by JohnnyWalkerDesign** [comment]
You misunderstand this request. I'm not talking about keeping the connection open. You get this alert after you've specifically ask the application to do something. If I'm asking TablePlus to do something, can't it reconnect automatically instead of making me click the top bar?

**Comment by JohnnyWalkerDesign** [comment]
> Hey @JohnnyWalkerDesign if you have any suggestion or question, feel free to email us at [nick@tableplus.com](mailto:nick@tableplus.com) there are 41 people who subscribe this repo and I don't want to spam their inbox 😛

I'm one of those 41. I'd bet almost none of us have signed up to receive notifications for every issue raised.

**Comment by nickcabral** [comment]
I agree with @JohnnyWalkerDesign's suggestion. Here's the current behavior, followed by what I believe to be an improved UX.

## Current Behavior
- The user tries to perform an action (eg. run a query) while disconnected.
- This error is shown:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/9586778/71604693-1685bd00-2b21-11ea-8dbc-992bec93e093.png">

- User clicks "OK".
- User clicks this area to attempt a reconnect:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/9586778/71604743-5187f080-2b21-11ea-8574-1efd5e490be1.png">
- Upon success, user re-runs the query they initially tried to run.

## Improved Behavior
- The user tries to perform an action while disconnected
- TablePlus attempts to reconnect automatically:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/9586778/71604800-af1c3d00-2b21-11ea-9089-a11805358d71.png">

- If the reconnect succeeds, TablePlus resumes the initially requested action (ie. run the query now that we're connected).
- If the reconnect fails, show an error since now we don't know how to proceed:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/9586778/71604887-2f42a280-2b22-11ea-9653-cb46e25168e2.png">

**Comment by huyphams** [comment]
The reason we don't do it because some users disconnect production on purpose (they don't want to mess up the production database), so it would rather show the popup instead of reconnecting automatically.

From the new version, if the connect fails due to the network, TablePlus will try to reconnect it when you click on the app (TablePlus will not reconnect if you disconnect using the menu). So I think this issue is resolved now. Please commend if you have any questions.
Thanks all

**Comment by thanhfphan** [comment]
Can we have an option on/off for this? Every time I make request to staging environment I have to Ctrl + Shift + R, so annoying
