### ISSUE TITLE
SQL Server Arabic Encoding  : ??????

### ISSUE THREAD

**Issue by adelemam** [TablePlus/TablePlus#1644]
When try to connect with SQL Server 2017 and later, and change any text column to arabic , it converts to ??????.

**Comment by huyphams** [comment]
Hi @adelemam thank you for the feedback, however, please do not remove the template issue. It not only helps me to investigate the issue faster but also reminds me of the issue when I revisit it in the future.

Regarding the issue, I could not help you because I don't know which version of TablePlus are you using so I assume you're using the latest version. Please double-check if you have set the connection encoding to UTF8.

<img width="797" alt="Screen Shot 2020-01-08 at 12 09 47 PM" src="https://user-images.githubusercontent.com/3654622/71994914-ff755800-320f-11ea-8b17-a1b5d013c455.png">

**Comment by adelemam** [comment]
thanks a lot and yes  I use latest version of the app, and we are usign SQL Server 2017
below is video screenshot for what is happening 
https://drive.google.com/open?id=1dThHtbebIeVDz2OjWMuu-OTtYozgl2cw

thanks

ks

**Comment by huyphams** [comment]
Hey @adelemam could you please try this build and see how's it going: https://www.dropbox.com/s/7mzayn6it9xfoqz/tableplus.dmg?dl=0
Thanks!

**Comment by adelemam** [comment]
wow , worked like a charm!! 
what was the issue?  and cannot I use the online one any more?

**Comment by huyphams** [comment]
the issue is that when updating a value which is encoded UTF8, the string must have the prefix N.
For example:
`UPDATE table <name> SET a_column = N'a unicode string'` instead of 
`UPDATE table <name> SET a_column = 'a unicode string' `
You can use that build as a official release, it can selfupdate. It just contains a hotfix.

**Comment by adelemam** [comment]
thanks a lot , appreciate your effort !!

**Comment by aquantwpi** [comment]
> the issue is that when updating a value which is encoded UTF8, the string must have the prefix N.
> For example:
> `UPDATE table <name> SET a_column = N'a unicode string'` instead of
> `UPDATE table <name> SET a_column = 'a unicode string' `
> You can use that build as a official release, it can selfupdate. It just contains a hotfix.

@huyphams , can you please send me the hotfix? :-) 
I have this issue with Japanese...
