### ISSUE TITLE
CPU to max with mysqldump error 2020 during backup

### ISSUE THREAD

**Issue by TheBabaYaga** [TablePlus/TablePlus#1656]
1. Driver: MySQL 5.7 on Mojave 10.14.5

2. Build: 286

3. The steps to reproduce this issue:

I've noticed when an export happens and mysqldump error 2020 is thrown, the CPU usage will go to max (even it's done exporting) and it does not go down without killing the application.

<img width="1161" alt="Screenshot 2020-01-14 at 10 39 30" src="https://user-images.githubusercontent.com/3961971/72333134-9c763c00-36bb-11ea-852c-8ccec9ac785a.png">

```
Backup database 'xxx'
Creating tunnel...
Dumping...
mysqldump: [Warning] Using a password on the command line interface can be insecure.

mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' bytes when dumping table `spen_xxx` at row: 988

Backup database completed
```

I could not attach a sample SQL since it's on a client's database, sorry.

**Comment by huyphams** [comment]
I just released the official build 290 which addressed this issue along with some new features, please check it, thanks @TheBabaYaga

**Comment by huyphams** [comment]
Thanks for confirming. The real issue is macOS process still trying to pipe empty values to the output despite the process has been terminated. It does not affect the backup file since TablePus omit the empty/null value but results in high CPU for nothing. It will go down after millions of pipe empty value.
I've closed the pipe as soon as the process terminated, it would not be a problem anymore.
