### ISSUE TITLE
[Bug] Copy Rows As > CSV doubles spaces

### ISSUE THREAD

**Issue by chrschmitz** [TablePlus/TablePlus#1659]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): SQLite 3.27.2

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 3.0 (286)

3. The steps to reproduce this issue:
1. Right click > Copy Rows As > CSV (or CSV with Header)
2. Paste clipboard to a text editor
3. Watch the result

This is a newly introduced bug. Older versions of TablePlus worked correctly.

Noted: If the bug is related to data, please attach an example SQL data.
[CopyPasteBug.sqlite3.zip](https://github.com/TablePlus/TablePlus/files/4070517/CopyPasteBug.sqlite3.zip)

**Comment by huyphams** [comment]
Hi @chrschmitz thanks for the report but I don't actually get the issue. I copy and paste it as you said and the result is correct. am I missing something here?

**Comment by chrschmitz** [comment]
Hi Huy, I sent you yesterday a private email with additional information and screenshots. Did you see that?

The bug is still present in v3.1.0 (Build 291).

**Comment by huyphams** [comment]
Hi @chrschmitz please choose the Quote if needed as the default CSV setting then it would correct the issue, I think you're using space as a quote so it will double the quote in the string. That was an intentional behavior.
Regarding the email, we're using nick@tableplus.com as email support for a long time and stop using other emails, maybe you've sent it to another email address.

**Comment by chrschmitz** [comment]
Yes, I used another email address. And yes, this was the problem. You can close this issue.

I am wondering why this setting was changed on my system. I never touched it.

**Comment by huyphams** [comment]
Thanks @chrschmitz for the confirmation! Yes, please use nick@tableplus.com now, sorry about that.
