### ISSUE TITLE
[BUG] IMPORT CSV

### ISSUE THREAD

**Issue by gfesj69** [TablePlus/TablePlus#1669]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
    MYSQL 5.6.46 MySQL Community Server (GPL)

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
    Version 3.1.0 (290)

3. The steps to reproduce this issue:
     FILE -> IMPORT -> FROM CSV

I try to import a CSV file into a table, the CSV has 1st line with fields, but it now discard it.

[Archive.zip](https://github.com/TablePlus/TablePlus/files/4086394/Archive.zip)

<img width="700" alt="Import" src="https://user-images.githubusercontent.com/49081014/72730731-b5c23100-3b70-11ea-90af-cf790bf53db3.png">

**Comment by huyphams** [comment]
Thanks @gfesj69 could you copy the table creation statement for me? I would like to create that table in my setup.

`the CSV has 1st line with fields, but it now discard it.`

I'm not sure that I understand it correctly, you want TablePlus skips the header?

**Comment by gfesj69** [comment]
Sorry, i typed wrong the last phrase.

but it not discard it

**Comment by gfesj69** [comment]
Here are the error.

<img width="413" alt="error" src="https://user-images.githubusercontent.com/49081014/72731077-abecfd80-3b71-11ea-8fb0-da6a7f044395.png">

**Comment by gfesj69** [comment]
The table and example to reproduce the error is here.

[Archive.zip](https://github.com/TablePlus/TablePlus/files/4086438/Archive.zip)

**Comment by huyphams** [comment]
Hi @gfesj69 thank you for the correction. I just checked it and it seems like a CSV issue. The column matched with the data is int, so it can not import the value (the second row in CSV) `DOCUMENT`, also because it's an int field, so it will not add quote and MySQL think it was a column.

<img width="705" alt="abc" src="https://user-images.githubusercontent.com/3654622/72731531-4a756080-3b6a-11ea-9372-551f5d2f788c.png">
