### ISSUE TITLE
Add Option To Display Hidden Files

### ISSUE THREAD

**Issue by inthedeepend** [TablePlus/TablePlus#171]
👋 - Thanks for Table Plus!

When adding a new connection that uses 'Over SSH', it would be great to have the option to display hidden files for example, when I am connecting to a vagrant box I need to go into the .vagrant directory which by default is hidden in this application. 

Let me know if there's anything I can do to help. 

Thank you once again - brilliant software.

**Comment by huyphams** [comment]
Thanks for the feedback. It's easy, I will add this option in next update.

**Comment by stebogit** [comment]
Hey I'm not sure how/if this was actually implemented, however I just stumbled upon a similar issue when importing a dump sql file that was inside a hidden folder (`.backup`), I was not able to see it in the import window when I was to choose the file. I had to temporarily rename the folder to be able to import the file.
How would I do it otherwise? Is there a way to see hidden files? I already have them visible by default in my computer.
