### ISSUE TITLE
How to refresh tables

### ISSUE THREAD

**Issue by kzhui125** [TablePlus/TablePlus#1748]
1. Which driver are you using and version of it:
MySQL 8.0.19

2. Which TablePlus build number are you using:
297

3. The steps to reproduce this issue:
open database test
open new SQL query and run the query
```sql
CREATE TABLE `t1` (
  `id` int NOT NULL,
  `c2` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
But I can't see the new table. And there is no refresh menu item.

**Comment by kzhui125** [comment]
Also, if I run query `drop table t2`, the table will not disappear.

**Comment by huyphams** [comment]
It's duplicated to https://github.com/TablePlus/TablePlus/issues/907

1. You can refresh by pressing Command + R or click the Refresh button on the top left.
2. Because you can run anything in Query editor, and it really hard to detect the executed queries contains created table/drop table to refresh the item list, also TablePlus has a pending state where the data is pending until you press Command + S so doing refresh automatically may leads to losing the changes.

**Comment by kzhui125** [comment]
@huyphams Thanks!
