### ISSUE TITLE
TablePlus no password required to log into PostgreSQL database

### ISSUE THREAD

**Issue by Maxeeezy** [TablePlus/TablePlus#1751]
PostgreSQL 12.1
  TablePlus build 282

The steps to reproduce this issue:

I created a database with PostgreSQL, then a user with a **password** that was granted access to the database and all SELECT/INSERT/etc. privileges on that database.

However, when I use TablePlus to login to my database, no password is required.
Usually, e.g. with mysql, the connection needs me to fill out the password, but not with PostgreSQL.

I feel this is not secure, how can I enable PostgreSQL to require the user's password to log in to the database?

**Comment by huyphams** [comment]
Hi @Maxeeezy thank you for reporting but this issue is not related to TablePlus. A database client such as TablePlus can't decide to connect to a server with or without a password. Please read the PostgreSQL documents for more details. Please let me know if you have any questions t (nick@tableplus.com)
