### ISSUE TITLE
Error importing from SQL

### ISSUE THREAD

**Issue by Jam0r85** [TablePlus/TablePlus#1768]
1. mysql  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)
2. 3.1.2 (296)

I've having an issue when exporting and importing from an SQL dump.

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"action_events" (
>   "id" bigint(20) unsigned NOT NULL AUTO_INCREMENT,
>   "batch_i' at line 1

It happens even if I don't export this table, it simply moves onto the next. I have no idea what I'm looking at or why this happens. Any ideas?

**Comment by ryanas** [comment]
Any progress on this? I'm hitting the same issue. It appears to be happening because it's generating the create statement using quotes instead of backquotes.

**Comment by huyphams** [comment]
I don't understand the issue @ryanas TablePlus uses backtick quote for MySQL, how did you get the quote instead of backtick quote?

**Comment by huyphams** [comment]
Maybe this issue was related to this: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes
Somehow you got the setting SQL_MODE=ANSI_QUOTES this is a bad practice and it will generate the SHOW CREATE TABLE <table_name> with results using double-quote => wrong.

Please remember that TablePlus does not generate the Table creation statement by itself. It is the result from SHOW CREATE TABLE <table_name>

**Comment by ryanas** [comment]
Thanks @huyphams. I've confirmed the database I was connecting to had ANSI_QUOTES set. Removing it resolved the problem.

**Comment by huyphams** [comment]
Thanks for confirming, but please be careful. it's not a default setting and it was there for reason (maybe), so please check your system before removing it.

**Comment by harshalone** [comment]
You can do this by going to the settings tab of your DO database, editing "Global SQL modes" and then removing ANSI_QUOTES. After that, reconnect with workbench or TablePlus, and you'll get the expected result.

See image here 
![here is the solution](https://i.imgur.com/o3VMMra.png?dl=0)
