### ISSUE TITLE
use checkbox to set `unsigned` independently

### ISSUE THREAD

**Issue by iiinsomnia** [TablePlus/TablePlus#1838]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 8.0.12

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 3.4.0, 304

3. The steps to reproduce this issue:

- Support checkbox for unsigned

Noted: If the bug is related to data, please attach an example SQL data.

![image](https://user-images.githubusercontent.com/6582246/80555529-14663900-8a03-11ea-804d-d275845d1275.png)

**Comment by huyphams** [comment]
Some users prefer to use "tab to edit". They want to stick with the keyboard and don't want to use a mouse. That's why we don't have any control that requires a mouse in the table structure. I know it's a trade-off but I believe it will be faster than using a checkbox. (I guess you're using Sequel Pro, is it right?)

**Comment by iiinsomnia** [comment]
haha, you are right.
