### ISSUE TITLE
New Feature: backup progress

### ISSUE THREAD

**Issue by raptor235** [TablePlus/TablePlus#1926]
Can we implement a progress bar for exports just like sequel pro has please.

<img src='http://www.flowpress.com/screenshots/screenshot%202020-05-30%20at%206.14.04%20AM.png'/>

**Comment by huyphams** [comment]
Hi @raptor235 there are two functions in TablePlus:
1. Backup/restore: use MySQL/PostgreSQL binaries, this function doesn't progress because MySQL, PostgreSQL does not have this feature.

2. Export/import: implemented by TablePlus team, this is similar to sequel pro and it has a progress bar.

<img width="504" alt="Screen Shot 2020-05-30 at 6 23 27 PM" src="https://user-images.githubusercontent.com/3654622/83327005-dd55a280-a2a2-11ea-8c6d-6793f0adeb10.png">
