### ISSUE TITLE
Cancel Long Running Query Button

### ISSUE THREAD

**Issue by akilism** [TablePlus/TablePlus#198]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

Postgres

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 84

3. The steps to reproduce this issue:

split sql query window into two 
run a long running query in one window
click to the other window 
click back to the long running query
can no longer cancel the query

**Comment by huyphams** [comment]
Sorry because the late response because I have tons of request every day. The cancel query function does not actually cancel all queries. It does empty the queue but not running query. Dealing with running query is very hard and depend on database library. I will try to improve this in some next updates.

**Comment by avdempsey** [comment]
When I cancel a query manually at the command line, TablePlus immediately restarts the query. Even clicking the cancel button doesn't seem to stop this.
