### ISSUE TITLE
Window outside of display

### ISSUE THREAD

**Issue by gett-thijssimonis** [TablePlus/TablePlus#1996]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
322

3. The steps to reproduce this issue:

In my work i'm switching to a lot of different workspaces(displays). Everytime if i'm working from a different display from the previous one and open an previous opened connection, the window is not centered and is going to the right outside the display. See this screenshot:
 ![Screenshot 2020-07-10 at 21 48 50](https://user-images.githubusercontent.com/55383747/87193107-45fb5a80-c2f8-11ea-8d87-8227dda66ba6.png)

**Comment by jaap** [comment]
Same issue here. A bit annoying.
It happens when connecting to a new server. At first I thought it happens when you use multiple displays, but sometimes this also happens on my Macbook without it being connected to any display.

![Item-0_and_AppleClockExtra_and_Siri_and_DisplaysExtra](https://user-images.githubusercontent.com/724492/89025195-b1987c80-d326-11ea-9808-89ca37fde74e.jpg)

**Comment by huyphams** [comment]
Hi guys, I'm sorry for the issue, this hot patch should fix the problem: https://www.dropbox.com/s/wy9l92h844lcef6/TablePlus.dmg?dl=0 Please let me know if you're still seeing it!
