### ISSUE TITLE
Command F (Filter) does not toggle

### ISSUE THREAD

**Issue by mikeerickson** [TablePlus/TablePlus#2004]
When the filter view is disabled, pressing Command-F properly goes to Filter.  However, pressing Command-F again to "toggle" find, it does not work and I must press the button in the lower right corner.

I have a very large monitor, so traveling to the bottom right of the window to turn off Filter is pretty bad for me.

**Comment by huyphams** [comment]
Thanks @mikeerickson are you using TablePlus for Windows? Which version of TablePlus do you have?

**Comment by mikeerickson** [comment]
No, this is on windows. I am using the latest (and I believe it is the beta release). I can get you an actual version number later this evening.  But I do "Check For Updates..." daily and I know I am on latest

**Comment by huyphams** [comment]
We don't have the beta release on Windows, thanks @mikeerickson we will check the TablePlus Windows now. Also, we will move this issue to the Windows repo: https://github.com/TablePlus/TablePlus-Windows

**Comment by mikeerickson** [comment]
Hello

I apologize, I wrote in error in the last reply.  I am indeed using on macOS and the version that I am currently using is 3.7.0 (327)

**Comment by huyphams** [comment]
Hi @mikeerickson thank you for confirming, I read the issue again and got the problem. I thought you have reported that the filter wasn't show up after pressing command + F but I'm wrong.
We don't use command + F hide the filter, we use it to focus the filter. So anytime you want to use the filter you can press command + F
We don't use it to toggle the filter because we want to focus on the filter quickly regardless of the filter state.

You can hide the filter using `ESC` all the shortcuts are right below the filter:

<img width="718" alt="Screen Shot 2020-07-18 at 11 01 43 AM" src="https://user-images.githubusercontent.com/3654622/87844298-13e48c80-c8e6-11ea-953e-0a6658ce63ae.png">

**Comment by mikeerickson** [comment]
Hello

OK, the reason I figured it was a toggle as due to this (see below).  The button tooltip shows that it "toggles" and uses Command-F for that action.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/183153/87844551-df83b880-c872-11ea-89e3-a1f53b6f401b.png">
