### ISSUE TITLE
Feature Request: Filter Columns by more than 1 column

### ISSUE THREAD

**Issue by mneuhaus** [TablePlus/TablePlus#201]
It would be awesome, if i could filter/search for more than 1 column in the sidebar view:

![](http://g.recordit.co/W88yU5JQhP.gif)

**Comment by huyphams** [comment]
I didn't get it, it would be great if you can clarify it for me, or some screenshot, it really helps.

**Comment by mneuhaus** [comment]
basically, apply each "term" that is seperated by a "," like the input itself is treated right now.
So, ```uid,filt``` should result in colums like ```uid```, ```filter_a```, ```filter_b```, etc to be displayed. I think using a comma should fit well since it can not be used as a character for fieldnames and is the same syntax for SQL field seperation.

**Comment by huyphams** [comment]
Understood, but I have an idea:

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/3654622/35519393-a9fbca64-0546-11e8-9b13-69f55691bdeb.png">

If we limit this column, it will also affect to the right-sider. I think this UX is a bit more clearly for the user than separated by a comma. (Because users might not know that they can search multiple columns by comma).

What do you think about this?

**Comment by mneuhaus** [comment]
i kinda like the "quickness" of the fuzzy column selection in the sidebar. imho separating it with a comma should be quite natural, since it's the same with selecting fields, etc.

**Comment by huyphams** [comment]
Yup, it could be "some kind of queries" like Google search does. 
For example: 
^abc => filter columns start with abc.
abc$ => filter columns end with abc.

So my suggest
So now we have abc|cde => filter columns match with (abc) OR (cde) the `|` probably a is bit nature than a comma.

**Comment by mneuhaus** [comment]
sounds good, i'd favor a comma but thats your decision :)

**Comment by huyphams** [comment]
I can support `comma` as an alias with `|` because as you said: there is no column contains a comma so it is no problem.
