### ISSUE TITLE
[Feature Request] "Add host" when managing users

### ISSUE THREAD

**Issue by ivankravets** [TablePlus/TablePlus#2045]
Hi,

Thanks for the amazing tool, **paid customer** here. 

Could you finalize porting https://sequelpro.com to TablePlus? I see you ported Sequel Pro's "User Management" but it's impossible to use it (can't add HOST to an account). I still use Sequel Pro to manage accounts and hosts. 

Regards, 
Ivan

**Comment by huyphams** [comment]
I believe that you can do the same thing in TablePlus by just create a new user with the same user name but a different host. Sequel Pro does the same thing, but the way they named the action could cause confusion/misunderstanding. There is no add host to a user in MySQL, Sequel Pro creates a new user with the same username but different host behind the scene.

**Comment by huyphams** [comment]
After adding a new user with the same username, TablePlus will group them into one section, just like Sequel Pro
<img width="1636" alt="Screen Shot 2020-08-24 at 11 13 11 AM" src="https://user-images.githubusercontent.com/3654622/91003184-dcf74a00-e5fa-11ea-8c74-2d77c5e7fd7f.png">

**Comment by ivankravets** [comment]
> There is no add host to a user in MySQL

Does MySQL have support for exporting results as JSON? Or, pinning table to the top? Or, creating favorites queries?

**Comment by huyphams** [comment]
Are you trying to say that JSON, pinning tables, and creating favorite are not MySQL? don't get me wrong, I'm not saying that "Add host" does not a real feature. I want to say that we can do the same thing with TablePlus, and Sequel Pro also does the same. The "Add host" just clone the current user and leave the host field empty.

**Comment by ivankravets** [comment]
I want to say that your team did great work with UI/UX. Now, you want me to look at your UI through the `CREATE USER... BY PASS` and SQL syntax.

Keep up great work and look on TablePlus from the user perspective, not as SQL engineer.

**Comment by ivankravets** [comment]
Right-click on USER could provide this contextual menu or standalone, as in Sequel Pro

<img width="236" alt="Screen Shot 2020-08-24 at 14 07 03" src="https://user-images.githubusercontent.com/1760209/91038216-189e0e00-e613-11ea-89a1-f8b275416abd.png">

**Comment by huyphams** [comment]
Yeah thanks, I appreciate it. The reason I pointed it out because you said `it's impossible to use it` so I think there would be a misunderstood.
I mean it, the `create a user` is not that bad and it's not `impossible to use it` I agree that it would save us some clicks but there are a lot of tasks in the backlog, and I would prefer some title like: `Clone user` instead of `Add host`.

**Comment by ivankravets** [comment]
> Clone user instead of Add host.

Why do you again think as a developer? Developer wants to give permission to the same user using **another host**. Let's imagine that another DB allows to do this without creating a new user with a password, etc? UI - this a wrapper around SQL. If you can build better UX, you should do this.

**Comment by huyphams** [comment]
I designed TablePlus and I tried to not influenced by any apps. I also received a lot of feedback from the user that came from Sequel Pro (I'm not using Sequel Pro before because I was a PostgreSQL user). Designing is hard, you can acquire a lot of users by copy a term of an existing app but in the long run, I don't think it would be a good idea.

Sometimes I feel that my app can educate users, so if I put term/feature that could lead them to a wrong assumption, I will not do that.

> Why do you again think as a developer?

So let's say, I wasn't a Sequel Pro user but came from CLI, and all I know was `adding a user` with a different host, how does `add host` make sense to me? I was looking for `add user/clone user` or something similar. I'm still thinking about it but as again, design UI/UX is hard, and we not just clone a feature.

**Comment by ivankravets** [comment]
Ok, let's if someone will come here. I still use both Sequel Pro (index management, user management, etc) and TablePlus (view data and navigation). It's not a problem for me to stay with Sequel Pro.

**Comment by huyphams** [comment]
I leave the issue open because I want people to go here and give their opinion. Thank you again for the suggestion.
