### ISSUE TITLE
Question: How do I make it so some users cannot see the contents of a table in TablePlus?

### ISSUE THREAD

**Issue by sdoggett** [TablePlus/TablePlus#2112]
How do I make it so some users cannot see the contents of a table in TablePlus? I'm aware that I cannot hide the table and column names from users, but I want to make it so that non-admin users see an empty table when they click on tables with private information in them.

**Comment by huyphams** [comment]
Hi @sdoggett I believe this issue is not related to TablePlus but it's the database feature, also TablePlus is a database client so it's not possible to hide a table.

The best solution is the role-based access control (permission), you could learn it from the database documents and it's unique depend on the database that you're using.
For example MySQL here: https://dev.mysql.com/doc/refman/8.0/en/grant-tables.html
