### ISSUE TITLE
Backup Fails with MariaDB

### ISSUE THREAD

**Issue by wayneforrest** [TablePlus/TablePlus#2118]
1. MariaDB 10.5.5

2. 3.9.1 build (342)

3.  Backup Database (Select MySQL 8.0). options selected:
      --routines,--lock-tables=false

Also note that the Message that the DB was successful, but has an error message.
:-) "A successful failure"

Error Message:
Backup database 'my_dbname'
Dumping...
mysqldump: [Warning] Using a password on the command line interface can be insecure.

mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'my_dbname' AND TABLE_NAME = 'Client';': Unknown table 'column_statistics' in information_schema (1109)

Backup database completed

**Comment by huyphams** [comment]
Hi @wayneforrest TablePlus use the official database binary to perform the backup, could you please try again with this flag? Also, it's not possible to know if the state of the process is successful or failed so we show "completed" instead of "successful"  at the end.
 
<img width="695" alt="Screen Shot 2020-10-05 at 11 51 27 AM" src="https://user-images.githubusercontent.com/3654622/95041527-227e5b00-0701-11eb-9301-4669a2084527.png">

**Comment by wayneforrest** [comment]
Thanks Henry, It worked!!! PERFECT and I used MySQL 8.0 in the selection.
I think the behaviour is probably because the table has JSON datatype; not sure on that though,

**Comment by huyphams** [comment]
Yeah, thank you for confirming.  MariaDB is a MySQL fork so I think MySQL 5.7 binary is better than MySQL 8.0 binary. I guess I can close this issue for now. Thanks again.
