### ISSUE TITLE
[Bug Report] TablePlus cannot delete certain table rows

### ISSUE THREAD

**Issue by vpoguru** [TablePlus/TablePlus#2159]
1. Which driver are you using and version of it: SQLite 3.31.0

2. Which TablePlus build number are you using: TablePlus 3.10.0 (348)

3. The steps to reproduce this issue:
Open the attached SQLite 3 database and try to delete a row from the table _ContinuousControlLinkage_.

[Test.zip](https://github.com/TablePlus/TablePlus/files/5444901/Test.zip)

You create a very complex SQL statement. Isn't it possible to create a simpler SQL statement using the rowid?

**Comment by huyphams** [comment]
Hi @chrschmitz thank you, that table does not contains any primary key and it's impossible to do the row companion because it has double value in it.
There are two possible solutions:
1. Add a primary key.
2. TablePlus should use the physical rowid as the primary key (SELECT rowid,* FROM  "ContinuousControlLinkage" LIMIT 300 OFFSET 0;)

TablePlus used to support physical column, however I removed it a long time ago because it's a hidden row.

**Comment by chrschmitz** [comment]
I cannot add a primary key, because this database will be processed by another tool, which expects exactly the current format (I gave you only one table as an example. The complete database has more tables.).

I remember that previous versions of TablePlus behaved differently.

Deleting rows with an SQL command works beautifully. But it was very convenient to point and click select rows, which should be deleted.

Although the rowid is not shown, the SQL command

    SELECT rowid, * FROM tablename;

shows the rowid plus the contents of the table.

Isn't it possible to query the rowid and generate the DELETE command as:

    DELETE FROM tablename WHERE rowid IN (a, b, c, ..., n)

Maybe this is even faster than the currently generated command and allows to delete more than 1,000 rows at once.

**Comment by chrschmitz** [comment]
It would be great if TablePlus would show the rowid similar to the line numbers in the SQL editor (with a smaller font).

![Screenshot](https://user-images.githubusercontent.com/13820940/99975097-15e1bf00-2da2-11eb-8057-4ec0cdc535a1.jpg)

**Comment by chrschmitz** [comment]
I finally understood the underlying problem. In tables without primary key, the generated DELETE expression lists all fields in the WHERE clause. If I a field contains a NULL value, the generated SQL expression looks like that:

     DELETE FROM "table" WHERE ("id" = '1' AND "value" = NULL);

If you copy this expression in the SQL editor and run it you will get "Query 1 OK", but the row will be not deleted.

The correct syntax should be:

     DELETE FROM "table" WHERE ("id" = '1' AND "value" IS NULL);

... or just remove fields containing a NULL value from the WHERE clause.

[Test.sqlite3.zip](https://github.com/TablePlus/TablePlus/files/5612440/Test.sqlite3.zip)

**Comment by huyphams** [comment]
Hi @chrschmitz thank you so much. I just updated the code, now TablePlus will use IS NULL instead of = NULL.

**Comment by chrschmitz** [comment]
@huyphams,  many thanks! This makes my life much easier :-)

**Comment by chrschmitz** [comment]
Hi @huyphams. The syntax has been also changed to "IS NULL" for the UPDATE function. This should be "= NULL".

**Comment by huyphams** [comment]
Hi @chrschmitz thanks, I fixed it: https://www.dropbox.com/s/kv55nmvms8n33ff/tableplus.dmg?dl=0

**Comment by clodal** [comment]
Adding a primary key as suggested by [huyphams](https://github.com/huyphams) worked for me:

`ALTER TABLE table_name ADD COLUMN id SERIAL PRIMARY KEY;`
