### ISSUE TITLE
Additional safety around running raw queries; Disable auto commit.

### ISSUE THREAD

**Issue by JAStanton** [TablePlus/TablePlus#230]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
PostgreSQL9.6.5

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
87

It would be great if there was additional safety nets around running raw queries in the app. Through the GUI all changes (deletes, updates) are temporarily made until they're committed. You can see the changes, you can be in a saftey mode which makes you double assert that this is what you want to do.

But no such safety for raw queries. It would be great if some additional prompts or safety nets (turning off auto-commit and having to type `COMMIT;` to the end of the query) around potentially dangerous updates, or deletes. (read only should be fine to run w/o)

**Comment by huyphams** [comment]
We have a button to set the level of safe mode:
Level 1. No warning.
Level 2. Warning when sending queries to the server.
Level 3. Prompt for the password.

We also have a preview button to see the raw queries. TablePlus swaps to a transaction begin <query> commit when you commit the change.

<img width="1271" alt="warning" src="https://user-images.githubusercontent.com/3654622/36057478-4655db9a-0e41-11e8-8d07-5d5f86eb9d88.png">

**Comment by JAStanton** [comment]
@huyphams these features are awesome for modifying rows, cols & tables with the gui, rows are highlighted and I know what I'm about to delete, or modify, I can see the query before I want to commit to it, it's absolutely fantastic. 

However lets jump over to old command line to give an example of how running raw queries can be dangerous:

If I ran this unknowingly dangerous command, I would see this:
> update thing set foo='bar';
> __103312__ ROWS UPDATED (and committed __omfg__!)

however with auto commit turned off I get this:
> update thing set foo='bar' WHERE id = 1;
> 1 ROW UPDATED (but the database wasn't modified at all)
> 
> commit;
> COMMITTED (woohoo)

I see how many rows I'm about to impact, and I confirm that this is indeed what I want to do. This is awesome and a much safer way to run queries via command line. I'd love this level of saftey in the GUI for raw queries.

From what I understand I can turn on Alert or Safe mode, but I wont know how many rows I'm impacted when I hit `commit` dialog confirm button. GUI modifies makes it clear w/ colors, but running raw queries in the app doesn't.

**Comment by samsamai** [comment]
It would be useful if there was a checkbox in the SQL window called something like `sandbox`, if ticked then the whole script would be wrapped with:

```BEGIN;
.
(1st block, possibly a DELETE)
.
(2nd block, possibly a SELECT)
.
ROLLBACK;```

Within the script the user can do a second select to see the result of the first block that they did.

**Comment by mrjones2014** [comment]
I would love to see this feature as well; JetBrains tools (DataGrip and IntelliJ IDEA) have an option to disable autocommit entirely on a per-connection basis.

**Comment by kes2464** [comment]
Any updates on this?
It would be very nice to have this feature. This is the only deal breaker for me.

**Comment by mrjones2014** [comment]
I've decided to switch back to JetBrains database tool because of this issue. Please please please implement this! I will certainly switch back once this is implemented!

**Comment by vnesek** [comment]
In addition, with commit/rollback control you can make changes to database in a session, review results in table editor and then commit/rollback. It would make TablePlus much more confortable to use.

**Comment by superandrew** [comment]
I add myself (license owner) and a co-worker (which is not buying a license for this very missing feature) to who would use this feature

**Comment by mritd** [comment]
When I purchased tableplus, I found that it can't turn off autocommit... This makes me feel frustrated.

**Comment by mpaniaguaff** [comment]
+1 - this is an essential feature!

**Comment by svyatogor** [comment]
I was about to switch to table plus from data grip, but without this feature I'd rather wait.

**Comment by rayhvh** [comment]
I also really need this feature. I've deleted thousends of rows unwillingly by misplacing an ; or my cursor. 
I want to know how much im about to delete!

**Comment by jtcloud** [comment]
This issue is opened for 2 years and we're still unable to disable auto-commit?

**Comment by svyatogor** [comment]
Turns out you can sort of achieve this. You just have to "BEGIN;" transaction first and then all queries will be in that transaction. Then you can update, inspect results and commit or rollback.

**Comment by huyphams** [comment]
That is a SQL feature @svyatogor the reason we do not add BEGIN and COMMIT automatically because, clearly the user could do this by themselves.

1. If we do this, many users will not understand what is going on behind the scenes.
 - The user who don't have transaction SQL  knowledge will not understand it, but they will find it easy because they can do some update query safely.
 - Users who have transaction SQL. Some of theme want to do it themselves (by adding begin, commit) and they may not know that TablePlus add it without their awareness.
 2. Not all queries could be reverted by transaction. DDL query (such as drop table, add column) could not be reverted after you run it.
 
 So adding BEGIN/COMMIT could cause a lot of trouble (with little benefit). So we will not do this. You can enable safe mode instead.

**Comment by adis-io** [comment]
Use https://www.pgcli.com/ for testing transactions

**Comment by cesarvspr** [comment]
Its 2024 I think we can reopen this. @huyphams the idea here is that only those which understand this feature and how Transactions work will enable this.

**Comment by devdyaya** [comment]
The software would really be perfect if it had the ability to prevent inadvertent execution of raw queries. 
We have all had the experience of inadvertently committing an unintended query in a production environment at one time or another. We want to make sure that we have to explicitly perform a transaction (BEGIN) in order to make changes to the database, instead of being alerted to do so.

I sincerely hope for this feature, because humans gradually lose their attention span even after setting alerts, and mankind will not overcome this even in 2024.

**Comment by huyphams** [comment]
Hi @devdyaya did you enable the safemode on Production?

**Comment by devdyaya** [comment]
Hi @huyphams, of course I have enabled it.
(Fortunately, I've never had an accident with Tableplus)
