### ISSUE TITLE
Support column comment

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#237]
It would be great if TablePlus can support column comment. Frequently that is crucial to understanding what a column really is.

**Comment by randomstrings** [comment]
Looking forward to this feature! Congrats on a really nice app!

**Comment by huyphams** [comment]
https://github.com/TablePlus/TablePlus/issues/305
https://github.com/TablePlus/TablePlus/issues/372
it's still `work in progress` but now we can see the comment (PostgreSQL and MySQL) and edit (PostgreSQL) the column comment:
Download: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

**Comment by randomstrings** [comment]
Excellent! 

Understood that it's a work-in-progess. Just my observations so far (minor nit-picks):

1. Would be nice if the comment column would *not* re-size (shorten) after saving comment: https://www.dropbox.com/s/8jpuhbh9t6xba8h/column_length_changes.mov?dl=0

2. Would be nice if the comment column would default to fill available table width instead of (shorter) fixed/standard-width (which cuts off text): https://www.dropbox.com/s/xtsm20wv9gsli3b/short_column.png?dl=0

Thanks for the awesome work!
