### ISSUE TITLE
FEATURE REQUEST: Ability to exclude tables from backup

### ISSUE THREAD

**Issue by Robio** [TablePlus/TablePlus#2406]
Would be helpful to be able to select tables to exclude from a backup.

Also, progress indicator for back process would helpful.

**Comment by huyphams** [comment]
We are using mysqldump for the task, so you can read the docs for more flag (include skip table) https://stackoverflow.com/questions/425158/skip-certain-tables-with-mysqldump

there is nothing we can do to show the progress because mysqldump does not support it. You can try the export feature instead.

**Comment by Robio** [comment]
Thanks for the information.
