### ISSUE TITLE
Keyboard shortcuts requested

### ISSUE THREAD

**Issue by richcorbs** [TablePlus/TablePlus#241]
I'd like to request/suggest a couple of keyboard shortcut enhancements:

- Keyboard shortcuts to switch between "Table Data" view and "Table Structure" view (maybe Cmd-1 and Cmd-2?)
- Keyboard shortcut to get to the "columns" feature of the "Data" view.
- Keyboard shortcut to get to the "filter" input at the bottom of the "Data" view.
- Modifiable keyboard shortcuts (open query, run query, etc)

**Comment by huyphams** [comment]
Here some:
- Keyboard shortcuts to switch between "Table Data" view and "Table Structure" view (maybe Cmd-1 and Cmd-2?): `commadn + shift + ]` and `commadn + shift + [` but I need improve it because it does not work when table lose focus.
- Keyboard shortcut to get to the "columns" feature of the "Data" view: I don't understand `column features`, you mean the right panel? you can press `space` to toggle right panel.
- Keyboard shortcut to get to the "filter" input at the bottom of the "Data" view: `command + F`
- Modifiable keyboard shortcuts (open query, run query, etc): `command + E` to open a SQL Query if current tab is not a SQL Query tab. Command + E, Command + Return (or Command + Shift + E, Command + Shift + Return) to execute queries.

I'm working on a feature allows user change all the shortcut keys.

**Comment by richcorbs** [comment]
Thanks for the response.

By column feature I mean the feature where you can set the columns you want
displayed in the data table.

**Comment by huyphams** [comment]
@richcorbs please upgrade to build 88, it has all the shortcut key 😄 
You can press: command + shift + F to start filter columns.

**Comment by jerryklimcik** [comment]
I know that this thread is already closed for some time but can you update [this cheat sheet](https://tableplus.io/blog/2018/02/shortcut-keys.html)? Or is there any other list of shortcuts keys? Some official list would be fine. Thank you.

**Comment by huyphams** [comment]
Hi, please hover the mouse over the button, you will see the shortcut or you can checkout FAQs, there is an answer for it.

**Comment by elliot40404** [comment]
Do the shortcuts only work on paid version?
