### ISSUE TITLE
Windows version laggy when scrolling vertically or horizontally

### ISSUE THREAD

**Issue by yawhide** [TablePlus/TablePlus#2412]
I am on a desktop with a decent desktop cpu. When I scroll vertically or horizontally, it lags super hard. I dont remember seeing this when using this product on a macbook air with a WAYYY less powerful cpu. 

I tried lowering the number of rows to automatically load from 300 to 40 and it still lags. The cpu from task manager goes from 0.5% to about 20% when I continuously scroll.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
postgresql 10

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
164

3. The steps to reproduce this issue:
Use the product on a windows 10 machine.

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by yawhide** [comment]
it is actually just any operation is lagging.

click from one tab to another, lag.
click to the next page at the bottom right, lag.

why is every action I am doing laggy? haha

**Comment by huyphams** [comment]
Hi @yawhide thanks for letting us know. It is one of the known issues of TablePlus Windows. The limitation of .Net grid view makes it lag.  We're working on the new grid view (we build it from the ground to solve this issue) but it has not done yet.

I'm closing this issue because this is the macOS repo and it doesn't have this issue. Windows repo is here: https://github.com/TablePlus/TablePlus-Windows/issues

**Comment by yawhide** [comment]
woops sorry about that!

**Comment by huyphams** [comment]
You can follow or submit an issue on the Windows repo or check the changelogs here: https://tableplus.com/win/changelog
