### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by akicreative** [TablePlus/TablePlus#2458]
I have been using for a few months now and overall I enjoy the app. My one painpoint, and I find this a huge issue is the compactness of the top toolbar. I understand it was a decision to jam everything in without much padding, but how many times a day do I push a button when I'm trying to move the window? Too many!

**Comment by huyphams** [comment]
Hi @akicreative please do not remove the issue template question. It helps us to track the issue.
1. You can always click to the title bar to move the app, no need to click on the space between the button.
2. You can custom the toolbar, removing, adding more button as well as space because it is a macOS application standard. Like this (right click on toolbar).
<img width="551" alt="Screen Shot 2021-07-21 at 22 42 17" src="https://user-images.githubusercontent.com/3654622/126518195-a4492e79-0891-4cd1-b678-628e68c140ef.png">
Result:

<img width="1259" alt="Screen Shot 2021-07-21 at 22 43 07" src="https://user-images.githubusercontent.com/3654622/126518313-c5f29f76-f0b9-42a3-b330-13b13727d2e8.png">
