### ISSUE TITLE
Auto-formatting always capitalises user keyboard when I have a table called user

### ISSUE THREAD

**Issue by jpike88** [TablePlus/TablePlus#2490]
### Please anwser the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
mysql

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 4.1.2 (382)

3. The steps to reproduce this issue:
Just have a table called user... and auto format a query referencing the user table. It changes the word user in capitals

**Comment by jpike88** [comment]
never mind it's in preferences.

**Comment by huyphams** [comment]
There are should be two entries in the auto completion 1 is keyword and 1 is table. If you choose the table, TablePlus will also add a bracket to it (to avoid syntax error because the table name conflict with the mysql reserve keywords).

And then TablePlus will remember your choice, next time, it will show the first result is user  - table over the user - keyword.

<img width="592" alt="Screen Shot 2021-08-30 at 10 40 58 AM" src="https://user-images.githubusercontent.com/3654622/131281943-b21e57c7-fb4d-457d-bc6e-67f060401eac.png">

**Comment by jpike88** [comment]
I was referring to the beautify button, that caused it always capitalize
