### ISSUE TITLE
Save workspace queries as *.sql file

### ISSUE THREAD

**Issue by nathanpalmer** [TablePlus/TablePlus#256]
I couldn't find this option anywhere but it would be great if we could save the workspace as a .sql file to reload later on. Sometimes I'm building up large set of related queries that I need to pull back later on.

**1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):**
PostgreSQL 9

**2. Which TablePlus build number are you using:**
87

**3. The steps to reproduce this issue:**
- Open a SQL query window
- Type in and run a query
- Look around for a save option, but can't find it.

**Comment by huyphams** [comment]
Hi, it's here.
<img width="630" alt="clickhere" src="https://user-images.githubusercontent.com/3654622/36184695-dca90ee0-1167-11e8-86c5-91d4e301995d.png">

**Comment by huyphams** [comment]
You can mark it as Favorite, it will appear in the left panel.

**Comment by nathanpalmer** [comment]
Oh! That's great that it has it. Though, I would expect it to show up in the File menu (especially since Open is already there.)

![screen shot 2018-02-14 at 5 39 37 pm](https://user-images.githubusercontent.com/125599/36231970-11ab79fc-11ae-11e8-88f8-a521f5b54ba8.png)

I like the Favorite feature, that could be useful. 

What I'm noticing though is this.

1. If I save a file, I can't just re-save it again easily with Cmd+S, or even by clicking File or the Gear and choosing Save. I'm force to use the "Save as" each time and select the file and tell it that I want it to overwrite. Is there is a shortcut to this or does it not exist?

2. I can't really tell if the file is modified (traditional text editor indicator such as an asterisk or dot.)

3. When I add it to the favorite, it's always "Untitled" or "Untitled-1". I've tried to open it up and change the name but it doesn't take. I'd expect it to atleast use the filename that I saved as or opened as, but also allow me to name it afterward.

**Comment by quelg** [comment]
+1 for this request. Needs to either automatically update file as you go or allow cmd+s. Definitely should be in the file save/as menu as that is the most natural place people look for. I didn't find it until I searched this thread!

Cheers

**Comment by locky28** [comment]
Ditto on searching GitHub to find this feature. I agree with adding it into the File Menu.

Maybe adding something into FAQ as a placeholder?

**Comment by sergiotapia-papa** [comment]
Was this feature ever added?

**Comment by ChrisjanWust** [comment]
Is any form of query saving possible on either the Windows or Linux version?

**Comment by michaelterryio** [comment]
This is the key feature which makes it impossible to fall in love with TablePlus.

The feedback loop for iterating queries is just to poor and I constantly have to rewrite queries that I've already done because the app has insufficient query peristence signals and requires too much "save" hygeine.

**Comment by huyphams** [comment]
It already supported, do you have any issue with the app @michaelterryio I don't understand your issue?

**Comment by michaelterryio** [comment]
Hi @huyphams

The issue is the implementation choices. Check the upvotes above...

There's no way to either turn on continuous saving or let `cmd-s` save a query.

## Option 1: Link query windows to saved sidebar entries

For example, if I save a query in the sidebar, I want you to automatically link my query pane to that saved entry. And if I load that saved entry, I want my query window to be connected to it. Then you could either have a toggle to enable continuous save or let me hit `cmd-s` to update it in the sidebar. This is how I expcted it to work because it's a pretty common interface design,

I can imagine the data model behind-the-scenes doesn't make this a trivial change, but it's important enough to do. If you have to create a new object that can house multiple semi-colon delimited queries in one object, that would be well worth it.

## Option 2: Link query panes to file objects

Option 1 is much preferable, but I could live with at least this option.

As it stands, if I save the contents of a query pane to the Finder, they are disconnected. No `Save` option appears in `File` menu.

-------

The upshot of all this is that, as I tweak a query, I have to remember that I tweaked it, even though I'm probably under time pressure and juggling several other applications, code windows, and needs-of-the business, and then I have to laboriously either copy/paste the contents back to my sidebar entry (whcih I also have to remember what I called it) or do another `Save as...` in the Finder.

That's just slow, hard and uncertain, so it creates a lot of rework.

Maybe there are other ways for the app to help me with this instead, but this is what comes to mind. Ultimately, want to build up a library of named queries with ease and pain-free, and not constantly fret that I'm losing work.

**Comment by huyphams** [comment]
1. You should create a query on the Save Queries tab, then the app will save the query, or it will save when you hit command + S (if you turn off auto-save).
2. You can rename the query by right click on it => rename
3. You can double-click to the query to open it.

I believe you feedback is only related to the "Save As" function... where you want to to be automatically save the file and link the file to the tab for further edit?

**Comment by michaelterryio** [comment]
Yes, exactly.

**Comment by huyphams** [comment]
You may want to try this patch: https://www.dropbox.com/scl/fi/s0z4zqny5947eg2qhqw16/TablePlus.dmg?rlkey=76jzdex2woe2ib6epa3r6ibxs&dl=0

I have added another solution where it should work for all existing use-cases (where it will not override the tmp queries).

**Comment by huyphams** [comment]
It has been released in the build 524
