### ISSUE TITLE
feat: disable tab navigation

### ISSUE THREAD

**Issue by gjuchault** [TablePlus/TablePlus#259]
Hi,

It could be nice to disable tab navigation (in free version at least) or to customize double clicking in a table. As soon as I forget to close tabs and double-click a table, I get the popup, which is a bit annoying.

Thanks :)

**Comment by huyphams** [comment]
Disable tab navigation can create a weird behavior and not consistent.

And tbh, if I disable it, somehow TablePlus team will end up with no sales, and there are no new version
 or new feature anymore😄

**Comment by gjuchault** [comment]
I was talking of an option : opening a new tab each time you click a link is not something everyone want to do.

In a browser, you usually click Cmd + Click to open in a new tab, but a simple click will open in same tab.

**Comment by huyphams** [comment]
`I was talking of an option : opening a new tab each time you click a link is not something everyone want to do.` => No, this is normal behavior because all the editor does the same thing, and I didn't see any user complain about it. All the TablePlus user emailed me complain about tab behavior is in free version.

Not annoying => no sales => the project is dead. The user wants a good product, but don't want to get annoyed when using the free version. If they didn't get annoyed why they buy it?

If user wants to use an open source (which is completely free), with a small project like TablePlus, somehow it will end up like this: https://github.com/zendframework/zend-servicemanager/issues/235#issuecomment-360050437

Btw, we are just a small team self-funding in this project, we want to make a better tool, hope you can enjoy the app and support us.

**Comment by gjuchault** [comment]
> Not annoying => no sales => the project is dead. The user wants a good product, but don't want to get annoyed when using the free version. If they didn't get annoyed why they buy it?

I'm not sure it works like you say. If they get annoyed, they either deal with it (-> sublime text warning every X saves), either they buy the software, or they use some illegal version.
The other way is to avoid annoying people, but still without offering them the feature.
For example the Dark Theme in TablePlus seems cool : if you click on the option, you get the alert. If you don't click on it you don't get the alert.

I'm not sure why you're talking about open-source software, as it is not the point here.

I'm very happy with TablePlus, I was just saying that annoying people with ads doesn't make them buy the product : offering them features they need will.

**Comment by huyphams** [comment]
As I said, we offered multiple tabs and workspaces are premium features (and we mentioned it clearly in our pricing.)
The reason we keep 2 tabs in free version because it's necessary for users, who click on a foreign key.

TablePlus free tier is good enough for basic users, but if you are an advanced user and you use the app heavily, you might want to buy it.

**Comment by gjuchault** [comment]
Allright, I guess we can close this then

**Comment by cloverich** [comment]
> No, this is normal behavior because all the editors does the same thing, and I didn't see any user complain about it.

Postico, a similar native macOS app, behaves like I and OP described above. This is also how web browsers behave (default same tab, you can optionally open link in new tab). This is an important feature to me.

**Comment by huyphams** [comment]
@cloverich TablePlus doesn't open a new tab in every click. It only opens a new tab if you modify the content of the current tab. it's important to keep tracking the current data instead of replacing the tab content.

**Comment by cloverich** [comment]
@huyphams thank you for the reply. I understand how TablePlus handles it and see the similarity to other editors (i.e. double clicking, or editing pin the tab). I just overall prefer how Postico handles it.

>  it's important to keep tracking the current data instead of replacing the tab content.

Postico handles this by maintaining the change while allowing you to navigate away. If you navigate back to your edit (ex: to the Table you were editing) the last edit will be present. If you try to close the app (or tab) without saving the change, it gives you a warning. 

I completely understand if this feature / behavior is not on your roadmap. I just wanted to clarify that it is conceptually separate from user complaints (about purchasing the app), and that comparable applications have implemented this behavior. Every user is a little different so of course its your call. For me, this is one of two features that keeps me using my (purchased) Postico install instead of deleting it and purchasing TablePlus (the other I've sent feedback on separately). I hope that is helpful.

**Comment by huyphams** [comment]
Thanks @cloverich for the insight. It's faster for the users who want to use gesture (swipe left-right) to navigate between tables. I've actually thought about that issue but it won't work in some important cases.
For example:
TablePlus does auto swap all the pending changes in `one` transaction, that means you can open multiple tables at the same time and modify the content, after preview all the changes you can safely commit it. The current design makes it clear.
In Postico, you have to do it one by one, because it only allows you to commit the changes in one table, then you have to switch to the other table and find the data to delete. Sometimes, once is related to others, and it's hard to keep track. I know we can open multiple tabs but it would init the connection every time.

**Comment by TheGitPanda** [comment]
As a 2 year user of TablePlus I am grateful for the free version. I was tempted to purchase today due to the annoying tabs. But realised it would cost me £75 (~$95). TablePlus is no doubt the best app i've used for SQL but this is 
not a price I would pay! I'd even consider a stretch to £50. Such a shame.

I recommend folks check out Beehive Studio, it may offer you enough. For me I've chosen to part way with TablePlus and acclimatise to phpStorm's built in SQL Tools.

**Comment by mempler** [comment]
Man i wish tableplus wasnt so god damn expensive that i have to sell half my organ for it. some of us cant just spit out like 100 bucks sadly
