### ISSUE TITLE
Make Beautify Customizable

### ISSUE THREAD

**Issue by timscott** [TablePlus/TablePlus#273]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 9.4.4

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

88

3. The steps to reproduce this issue:

This is a feature request.

Beauty is in the eye of the beholder, is it not!? I find this particularly true for SQL. For example, SHOUTING CASE is particularly painful to my eyes. This is one of the many beautification choices I would like to be able to make. What's the chance Beautify can be customizable?

The most basic things I would like to change:

* capitlaization
* two space indentions
* conjunction at end of condition
* closing parent on new line
* modifier on same line a keyword in only one, for example:

```sql
select *
from users
```
not

```sql
select
    *
from
    users
```

**Comment by huyphams** [comment]
Probably I will expose beautify API, then you can add a beautify plugin to TablePlus:
some resource I found:
- https://github.com/zeroturnaround/sql-formatter
- https://github.com/jdorn/sql-formatter
- https://github.com/vkiryukhin/vkBeautify

**Comment by timscott** [comment]
@huyphams Awesome! Maybe not me, but somebody will do it. Or maybe me. :)

**Comment by huyphams** [comment]
The reason we expose API and build the plugin system because we don't want to include all the things in one tool (TablePlus can become a complicated application for new users). if people want a feature, they simply install it.
About the plugin, most important features: import, export, viewers process data will be implemented and maintained by TablePlus team. If you want to contribute to plugin, you are welcome 🙌

**Comment by timscott** [comment]
@huyphams. Smart. As an Atom fan, I love the plugin model. I’m confident I’ll see a lot of great plugins.

**Comment by coisnepe** [comment]
Hey, I had the same question and found this issue.
@huyphams Are you aware of any plugin that's been made to address this concern?

**Comment by huyphams** [comment]
I didn't have time to complete the plugin system (because it needs a lot of work), but I can easily expose some more function related to SQL Query, such as:
- Get the current SQL in SQL Query screen.
- Support replace text in range, parse query and shortcut key.
- Support hook and change the default for format SQL function.
- A basic document and examples.
 
With all the APIs above, you can easily to integrate your favorite SQL format.
I will do it in some next updates (I estimate this task can be done less than 2 weeks, from now).

**Comment by huyphams** [comment]
Hey guys, I have a good news for you:
Now you can choose your own SQL Format.
Download TablePlus here: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
The plugin is here: https://github.com/TablePlus/sql-formatter
@timscott @coisnepe

**Comment by timscott** [comment]
@huyphams I installed it, but when I try to use it as shown, it does not seem to do anything. I restarted TablePlus. Same.

**Comment by alvint** [comment]
Just taking a wild guess, but did you also download the new version of TablePlus that he linked to? Previous versions probably don't expose the API calls that the plugin requires.

**Comment by huyphams** [comment]
Yup, that's true. As @alvint mentioned, you need to download the new build which has new SQL Query APIs.

**Comment by timscott** [comment]
TablePlus  updated automatically immediately before I install the plug-in. Maybe still not current enough. I’ll make sure I have the right version.

**Comment by alvint** [comment]
@timscott Yep, the automatic updates will install the regular release version again. I accidentally updated away my Oracle support once.  :)

**Comment by tylerb** [comment]
This formatter is already SO MUCH BETTER than the previous one. Thanks for exposing this.

Any way I can change the hotkey so that `cmd+i` runs this formatter plugin instead of having to use `ctrl+i`?

**Comment by huyphams** [comment]
Hi @tylerb you can change the shortcut key in manifest.js but it's conflict with the existing shortcut key.
I'm working on the feature that supports dev change the default of Beautify button (like it does with Execute button) and the shortcut linked with it.

**Comment by tylerb** [comment]
Fantastic! Thanks!
