### ISSUE TITLE
Can't add columns in Oracle

### ISSUE THREAD

**Issue by minesunny** [TablePlus/TablePlus#2751]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 11g
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 433
3. The steps to reproduce this issue:
Create a table in Oracle, than try to add columns in that table,after save and fresh table ；
Noted: If the bug is related to data, please attach an example SQL data.

https://user-images.githubusercontent.com/98507458/180341764-e546d334-7917-4717-b8d1-3cd8a93b27d6.mp4

**Comment by huyphams** [comment]
Hi @minesunny if you have a chance, please try this hot patch: https://www.dropbox.com/s/90gpcq6vv6pi6n1/TablePlus.dmg?dl=0 it would resolve the issue.

We have a plan to discontinue Oracle in the future release (currently it is on beta release - not an official release) because we got so much trouble with Oracle and it could affect our reputation as users give bad reviews everywhere because of this.
