### ISSUE TITLE
MS SQL 2012, cannot see tables, views, etc under "Items"

### ISSUE THREAD

**Issue by felipehn** [TablePlus/TablePlus#284]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Microsoft SQL Server 2012

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 1.0 (90)

3. The steps to reproduce this issue:
I can log into the DB with no issues, but after selecting the Database I cannot see any tables, functions, store procedures, etc.; I'm able to execute select statements and I get results, I just don't see the tables under "Items" and that makes it very difficult to work.

thanks,
Felipe.
![screenshot](https://user-images.githubusercontent.com/3174309/36636145-ec20ef5e-1974-11e8-9a67-03625bc66fda.png)

**Comment by huyphams** [comment]
Hi @felipehn could you try to run this query: SELECT table_name,table_schema,table_type FROM information_schema.tables WHERE TABLE_CATALOG = `Your database name`; is it return any result?

**Comment by felipehn** [comment]
no results, all empty

**Comment by huyphams** [comment]
Thanks, could you try again with this query:

SELECT [table_name],[table_schema],[table_type] FROM [`Your database name here`].[information_schema].[tables];

This query is using to get tables, if it returns empty that means TablePlus will not show any tables.

**Comment by felipehn** [comment]
I’m getting "Invalid object name”, if I for “master” I get those tables (the ones in master) as records though 

I usually do select * from [database name].sys.tables don’t know if that helps

thanks,
Felipe.

**Comment by ryanq** [comment]
I thought I was seeing this today. I had a table defined that I could select from, but it didn't show up in the sidebar. I could bring it up in a tab with the open anything shortcut. It turned out to be that the selected schema (dbo) wasn't the one that contained the table. Selecting the proper schema showed the table under the items heading.

I thought I'd post here in case that was the issue here.

**Comment by linkdesu** [comment]
Mysql 8 can not see tables, the correct query should be `... WHERE table_schema = ...` .

This makes new users really disappointed.

**Comment by huyphams** [comment]
Hey @linkdesu let me test with MySQL 8, but it should be an other issue.

**Comment by huyphams** [comment]
Hey @linkdesu please check this issue: https://github.com/TablePlus/TablePlus/issues/392
TablePlus supports MySQL 8.0 now.

**Comment by felipehn** [comment]
still doesn’t work, but your select statement below works if the table “SYS” changes to “sys”,
this database is case sensitive for some reason, it was set with Collation Latin1_General_100_BIN
so i guess if you set that SYS to sys, it will work.

sorry for the inconvenience, and thanks a lot for the support

your program is great!

thanks,
Felipe.

**Comment by huyphams** [comment]
Cool, Thank you so much.
Microsoft SQL Server is weird. Some user reported that the `information_schema` not work but after changing to `INFORMATION_SCHEMA` (upper case) it works.

But in your case, the information_schema completely not work, so I think I need to change all the queries to not using `information_schema`.

This bug will be completely fixed in the next update. I still need to inform you and some other users. when all users confirm it works, the update will be released.

**Comment by huyphams** [comment]
Hi @felipehn I have changed all the queries to get rid of `information_schema` can you give this build a try? https://www.dropbox.com/s/d13ucw1agrnhqcl/TablePlus.zip?dl=0

**Comment by felipehn** [comment]
this one did it!


thanks,
Felipe.

**Comment by huyphams** [comment]
Great, it will be released tomorrow. Thank you 👍

**Comment by huyphams** [comment]
It's released in build 106, thanks for reporting the issue.
