### ISSUE TITLE
[FEATURE REQUEST] - Expand Tables to See Columns

### ISSUE THREAD

**Issue by charliegriefer** [TablePlus/TablePlus#3094]
Most other DB GUIs that I've used (DataGrip, DBeaver, and even MySQL Workbench) allow you to expand/collapse tables to see things like columns, keys, etc.

I recognize that with TablePlus I can open the table structure, but screen real estate is at a premium, and I'd really love to just be able to expand a table in the tables view to see keys, columns, and the like.

<img width="334" alt="Screenshot 2023-09-21 at 11 36 40 AM" src="https://github.com/TablePlus/TablePlus/assets/96950/2a8d191a-b135-4168-9eb7-26ef0aeaa391">

**Comment by huyphams** [comment]
Hi @charliegriefer you may want to try our newest app which supports this feature.
https://boltsql.com

**Comment by charliegriefer** [comment]
Hey @huyphams ...

So is boltsql replacing TablePlus? 

I literally just bought a TablePlus license 7 days ago :\

**Comment by huyphams** [comment]
It won't replace TablePlus. TablePlus will be add many more feature in the up coming months. Include this feature.

**Comment by charliegriefer** [comment]
Sounds good. I'll likely stick with TablePlus then, as I'm just a single developer. Can't really justify the annual license for boltsql since the collaboration features really wouldn't benefit me much.

Will just hope to see the expandable tables in TablePlus sooner rather than later ;) 

Thank you!

**Comment by huyphams** [comment]
Bolt SQL pricing model is subscription because it has variable cost (server, api...).
So I think it is more suitable for company than individual users 😄

**Comment by charliegriefer** [comment]
Hi @huyphams ... perhaps I shouldn't have closed this issue? Is there a ticket currently to implement this feature?

**Comment by FlyingClipper** [comment]
Just wanted to second this as I truly miss this coming from SSMS and have no plans to move to BoltSQL.  It's extremely helpful as a quick reference when working in the SQL editor.  Otherwise I love TablePlus, this is truly the only feature I've missed.

**Comment by charliegriefer** [comment]
> Just wanted to second this as I truly miss this coming from SSMS and have no plans to move to BoltSQL. It's extremely helpful as a quick reference when working in the SQL editor. Otherwise I love TablePlus, this is truly the only feature I've missed.

Yup. This is the only thing keeping me on dBeaver instead of fully embracing Tables. Amazing to me that this is not a feature. And that 6 months after opening this issue, it's still not a feature.

**Comment by gentrytech** [comment]
Deal-breaker unless improved.

Not showing table column names in the left sidebar is a major deviation from long-standing SQL client conventions and has a real, measurable impact on productivity, especially when writing queries.

This feature is effectively universal across serious SQL tools because it prevents constant context switching. When columns are visible in the schema tree, developers can reason about structure while writing SQL. Without it, you’re forced to bounce between tabs, queries, or table previews. That friction adds up fast.

What’s frustrating is that this isn’t an experimental UX decision; it’s a **major regression** from decades of established practice. There is no functional upside to hiding columns, and the downside is substantial enough that it pushes users toward other tools, even when they otherwise prefer TablePlus.

To be clear: this is not a niche request. Nearly every competing SQL client (both commercial and free) gets this right.

This is not about personal preference. It’s about baseline usability for SQL work. Hiding columns actively degrades the query-writing experience and breaks muscle memory for anyone coming from another client (which is… everyone).

TablePlus is otherwise excellent. That’s why this omission stands out so sharply. But until column names are visible in the sidebar, this remains a blocker for serious, day-to-day SQL development.

**Comment by charliegriefer** [comment]
I left Table Plus because this is an issue that I rely on. Been using DBeaver instead.

But I do love that Table Plus is a native app, so came back to grab a new license thinking, "SURELY THEY'VE FIXED THIS BY NOW".

Boggles my mind that they have not.

Boggles my mind more that @huyphams hasn't even bothered to give an update since telling me to try BoltSQL 2 1/2 years ago.

Just incredible.

**Comment by huyphams** [comment]
We've been working on it for a while, but it still has some issues and has not been merged into the main branch (available on macOS/Windows and Linux)
<img width="459" height="327" alt="Image" src="https://github.com/user-attachments/assets/00afef7a-1823-4331-b218-500b171ee91a" />

**Comment by charliegriefer** [comment]
It's been 2 1/2 years. This functionality is in your other app (boltsql). It's ok. Clearly not a priority for you and while there are a few of us for whom this is a deal-breaker, there are clearly enough folks who don't mind to keep you in business.

**Comment by huyphams** [comment]
We are merging this. The feature will be available in the next update but will be turned off by default. You can enable it in the app settings.  

We will close this issue for now. Thank you for your suggestions.
