### ISSUE TITLE
"Old" MySQL passwords not supported

### ISSUE THREAD

**Issue by nfgrilo** [TablePlus/TablePlus#314]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7.21

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 92

3. The steps to reproduce this issue:
Attempt a connection to a MySQL server using "old" passwords. The following error will be presented when trying to connect:

![screen shot 2018-03-08 at 09 52 33](https://user-images.githubusercontent.com/2744944/37144750-e37a1c2c-22b6-11e8-8624-4fd3fdea354d.png)

**Comment by huyphams** [comment]
Hi, @nfgrilo thanks for the feedback. Looks like I should add an option `use old authentication protocol.` to TablePlus.
https://forums.mysql.com/read.php?152,637958,638272#msg-638272

**Comment by huyphams** [comment]
Hey, @nfgrilo I'm sorry because it takes so longgg just for a small update. I have added compatible for the old MySQL from this build, can you give it a try?
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
<img width="552" alt="screen shot 2018-10-05 at 5 13 55 pm" src="https://user-images.githubusercontent.com/3654622/46529828-0cdfbc00-c8c2-11e8-9b08-cd7e2622817c.png">

**Comment by huyphams** [comment]
Related issue: https://github.com/TablePlus/TablePlus/issues/665

**Comment by comhernandez28** [comment]
Hello @huyphams I tried the build you linked and it wasn't working still. I replicated this exact same issue and am also having trouble with it. Should I reopen another issue and mention this one?

**Comment by huyphams** [comment]
Have you tried with the MariaDB driver @comhernandez28 ?

**Comment by comhernandez28** [comment]
I have not @huyphams I will give it a try
