### ISSUE TITLE
Cannot find where to add new Schema/Name space

### ISSUE THREAD

**Issue by mk-nickyang** [TablePlus/TablePlus#333]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**PostgreSQL 9.6.8**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**Build 93**

3. The steps to reproduce this issue:
I just cannot find where to create schema for the current database except for running SQL query. Forgive me if this question is too stupid. Thanks

[![Screenshot from Gyazo](https://gyazo.com/861263a2c24f084a853779f27a894bef/raw)](https://gyazo.com/861263a2c24f084a853779f27a894bef)

**Comment by huyphams** [comment]
Hi @mk-nickyang sorry because of the late response. Currently, TablePlus doesn't have a GUI for creating a schema. The only way to create it is using SQL Query. 
The reason why I didn't include it in TablePlus are:
1. Rarely using.
2. Not all TablePlus drivers support it (MySQL didn't have the schema).
3. TablePlus will not cover everything but the plugin. We are developing the plugin system that can extend TablePlus.

**Comment by huyphams** [comment]
Hey @sam-jg I just updated the UI, thanks for the excellent suggestion 👍 
<img width="1208" alt="ice" src="https://user-images.githubusercontent.com/3654622/37575067-a67bd960-2b57-11e8-8fa4-0ba3b927ed82.png">

**Comment by huyphams** [comment]
Hi guy, I added a GUI for creating a new schema in the upcoming update.
<img width="492" alt="screen shot 2019-02-25 at 1 47 28 pm" src="https://user-images.githubusercontent.com/3654622/53319038-e9b2b900-3903-11e9-9f39-0366022b1860.png">
