### ISSUE TITLE
"OracleSQLError(code: serverVersionNotSupported)" Version 6.1.0 (565)

### ISSUE THREAD

**Issue by natatkinson** [TablePlus/TablePlus#3340]
### Please answer the questions below, it helps us to keep track of the issue. Please do not ignore it or your issue will be closed.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Oracle

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): Version 6.1.0 (565)

3. The steps to reproduce this issue:
Connecting to Oracle server running version 12.1.0.2.170418 now fails

Which versions of Oracle server are supported by TablePlus?

**Comment by huyphams** [comment]
Hi @natatkinson 
Thank you for reaching out. Due to the limitations of the Oracle driver (they don't release an ARM driver for macOS), we moved on and updated our Oracle driver to thin mode (removed the instance client). More details: https://x.com/TablePlus/status/1804934916003525038 

You can download and keep the old build here: https://files.tableplus.com/macos/563/TablePlus.dmg

**Comment by eSkiSo** [comment]
They released it finaly:

https://www.oracle.com/pt/database/technologies/instant-client/downloads.html
![imagem](https://github.com/user-attachments/assets/7c58169f-910c-45fd-98ee-2ea504194424)

**Comment by huyphams** [comment]
please follow this issue as we will bring back on driver https://github.com/TablePlus/TablePlus/issues/3342
