### ISSUE TITLE
Getting OracleSQLError(code: uncleanShutdown)

### ISSUE THREAD

**Issue by jbstowe** [TablePlus/TablePlus#3341]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle that is bundled in with table plus

3. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Build 565 

4. The steps to reproduce this issue:
Trying to connect to any oracle database and getting the error "OracleSQLError(code: uncleanShutdown)" 

I have uninstalled and re-installed and continue to get the same error. Also, I uncheck Receive Beta Updates in the settings but it still keeps giving me that build (which appears to be a beta build) no matter what when connecting to an oracle database. Other databases (mysql for instance) work fine.

**Comment by huyphams** [comment]
Hi @jbstowe does it only happen in the recent update or this is the first time you use TablePlus?

**Comment by jbstowe** [comment]
Seems to only happen in the recent update, I had been using table plus with oracle with no issues for a year or so.

**Comment by huyphams** [comment]
Thank you for the info. Due to the limitations of the Oracle driver (they don't release an ARM driver for macOS), we moved on and updated our Oracle driver to thin mode (removed the instance client). More details: https://x.com/TablePlus/status/1804934916003525038 

You can download and keep the old build here: https://files.tableplus.com/macos/563/TablePlus.dmg

**Comment by jbstowe** [comment]
@huyphams Got it, thanks for the help!
