### ISSUE TITLE
Auto quote table names and attributes

### ISSUE THREAD

**Issue by sam-jg** [TablePlus/TablePlus#340]
Would be great if the SQL editor would automatically quote table names and attributes when they are selected from the auto-complete. This would be helpful because most DB's require you to double quote "" camel case tables and attributes.

I think this should be a setting turned off by default. The setting could also include an option to quote all tables and attributes or just the ones that require it.

**Comment by AlexandreGalois** [comment]
In addition to this, it looks like the standard queries generated by the UI when updating the view do not automatically quote/tick column names.

E.g. imagine a simple MySQL table with column names containing spaces:

**Test case:**

```
CREATE TABLE examples (\`position\` int, \`such column\` varchar(10), \`many genius\` int);
INSERT INTO examples VALUES (1, 'rofl', 10);
INSERT INTO examples VALUES (2, 'sniff', 8);
INSERT INTO examples VALUES (3, 'so meme', 2);
```

If you open this table in TablePlus UI and sort on "such column" it'll throw an error saying:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'column LIMIT 100 OFFSET 0' at line 1

Not 100% sure this is what causes it, but fact is when you remove the spaces the problem is gone. When you write the select query without the quotes it reproduces the same error.

PS: By no means this post means having these kind of column names is good practice..

**Comment by huyphams** [comment]
Hi @AlexandreGalois could you tell me more about your client version? Because TablePlus always add quotes in the auto-generated statement.

**Comment by huyphams** [comment]
Looks like it's a bug:  SELECT * FROM `nice`.`baba` ORDER BY `ch` Ee LIMIT 2000 OFFSET 0; the back stick was wrong position.

**Comment by AlexandreGalois** [comment]
Well, that was resolved pretty quickly :) Let me know if you need any further info.

**Comment by huyphams** [comment]
Hey @sam-jg TablePlus now supports adding quote:
https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0
Currently, it adds a quote automatically when table/column name has space or have both lower case and upper case.
