### ISSUE TITLE
CockroachDB Support

### ISSUE THREAD

**Issue by mholt** [TablePlus/TablePlus#374]
Not a bug report, but a feature request to support CockroachDB. Its admin interface doesn't support viewing tables and running queries, so it would be great to see that in TablePlus.

**Comment by huyphams** [comment]
CockroachDB uses PostgreSQL protocol to connect to its database. I will optimize it in the future (it's already on our roadmap).

**Comment by mholt** [comment]
Great! Yeah, it just seems to work somewhat but when I go to list the contents of a table, it says `ERROR:  column name "ctid" not found` -- that's the only error I have seen so far. Hopefully it won't take too long to do since you already have fantastic support for PostgreSQL. Thanks again!

**Comment by huyphams** [comment]
Hey @mholt I just added support for Cockroach DB (maybe there are some bugs) can you give it a try?

Download: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

<img width="712" alt="screen shot 2018-04-03 at 11 10 43 pm" src="https://user-images.githubusercontent.com/3654622/38261382-3eb74604-3794-11e8-89f0-04dd4d9d4734.png">

**Comment by mholt** [comment]
@huyphams Hey, this is great, from my basic testing it works! Wow. You're fast. That means you probably have a pretty good underlying design. Nicely done.

**Comment by codingconcepts** [comment]
@huyphams, thanks for adding CockroachDB support!

I've just had a little play with it myself and would second @mholt on the design sentiment!

One thing I've noticed that might be quite useful, would be to limit the available data types in the create table `data_type` dropdowns, so that it only contains those supported by CockroachDB (https://www.cockroachlabs.com/docs/stable/data-types.html).  It's possible to add `string` via manual entry but it'd be great to be able to select it :)

Thanks again!

**Comment by codingconcepts** [comment]
I'm not sure if this is a CockroachDB-specific error, but I'm trying to change the string array value `{"a","b","c"}` to `{"a","b","d"}` and receive the following:

![image](https://user-images.githubusercontent.com/10614665/38271288-fb22a25a-377d-11e8-9001-748e3b234253.png)

**Comment by huyphams** [comment]
This is the new build, it fixes many issues: https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0

Remaining:
- Auto convert '{}' syntax to Array[].
- Support data length in structure(example: STRING(20))
- Support create seq.

**Comment by codingconcepts** [comment]
This could very well be me being stupid but this is appears to be the same file (shasum wise)!

Is this definitely the new version, @huyphams?


Cheers!

Rob

**Comment by huyphams** [comment]
Hi @codingconcepts it's new build. I just updated the file on Dropbox (don't need to change the link).

**Comment by mholt** [comment]
I didn't compute a checksum but I can confirm it is different / improved.

Still needs a little work, but I like how it's coming along. I'll try to scrounge up some time to give more.specific feedback later.

**Comment by huyphams** [comment]
Hey, I think everybody here is using Cockroach every day so I distribute this build (because waiting is a pain):

https://www.dropbox.com/s/fghht69ib70jdpn/TablePlus.zip?dl=0 (till the same URL).

It's usable in common cases:
- Query.
- Update, delete, insert. (Now it supports transform array from {} to Array automatically).
And all the basic function.

Welcome any feedback 👍

**Comment by glerchundi** [comment]
@huyphams fantastic job!

I didn't test it out extensively but looks promising, will send a feedback.

Just one nit, there is a discrepancy between which extension CockroachDB expects for certificates and TablePlus allows to pick. CockroachDB searches (when using their cli with `--certs-dir`) for `*.crt` extensions (concretely for `ca.crt` and `client.<user>.crt`) but TablePlus requires these to be ending in `.pem`. If its possible it would ease our lives a little bit if TablePlus allowed the selection of `*.crt` files for certificates as well.

**Comment by mholt** [comment]
I don't know if it matters, but something to note is that .pem and .crt usually imply different encodings (at least in web server land): .crt is usually DER-encoded and PEM is of course PEM-encoded. That would make a difference when reading the file. If you only support one format, document that.
