### ISSUE TITLE
ability to run selected SQL statements

### ISSUE THREAD

**Issue by linuxjuggler** [TablePlus/TablePlus#378]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
99

3. The steps to reproduce this issue:

```sql
delimiter ;;

CREATE PROCEDURE `testing`(IN idx INT)
BEGIN
    SELECT `created_at`
    FROM `users`
	WHERE `id`=idx AND `deleted_at` IS NULL ORDER BY `created_at` DESC LIMIT 1;
END
;;
```
selecting the whole statement and then run `run selected` results `Query was empty`

meanwhile the same code works without any issues on sequel pro

![screen_shot_2018-04-09_at_12_38_40](https://user-images.githubusercontent.com/27624/38490932-202beef2-3bf3-11e8-93f7-d278734cf2d1.png)

**Comment by huyphams** [comment]
Hey thanks,
The reason TablePlus says it's empty because it tried to parse the statement into queries.

The main difference between TablePlus and Sequel Pro is Sequel Pro only parse the string into queries when you have not highlighted the string.

For example:
When you highlighted this string: `Select 1; Select 2`
TablePlus will try to parse it into query `Select 1` and `Select 2` but Sequel Pro send all the string to the server.

I will improve it in next update, thanks 👍

**Comment by linuxjuggler** [comment]
I got your point, and hope to see it fixed soon, as this affect anything related to creating functions and procedures ..

thanks again

**Comment by linuxjuggler** [comment]
thanks @huyphams, I'll look into it later when you release the build.
