### ISSUE TITLE
save connections on iCloud

### ISSUE THREAD

**Issue by FCO** [TablePlus/TablePlus#390]
This is a feature request.

It should be possible to save de connection details on iCloud, so I can connect to all my databases from any computer.

**Comment by huyphams** [comment]
Yup, we have a plan to support sync connections using private clouds: dropbox, google drive, icloud...

**Comment by eivindml** [comment]
Would love this as well.

Would be great if it's natively integrated with iCloud lik this, with icon etc: 

<img width="651" alt="skjermbilde 2018-05-04 kl 13 02 17" src="https://user-images.githubusercontent.com/202450/39624963-aba997d4-4f9b-11e8-895d-db69b3934d4e.png">

**Comment by jorgespiessens** [comment]
+1

**Comment by mauropiccini** [comment]
+1

**Comment by upwebdesign** [comment]
+1

**Comment by jpike88** [comment]
+1

**Comment by upwebdesign** [comment]
@huyphams Im confused, why is this closed? Same with #968. Was there a release with this feature? Maybe an explanation will clear this up.

**Comment by huyphams** [comment]
We added an ability to change the app data path, so you can sync it via private clouds (iCloud, Dropbox, GitHub, Google, one drive etc...) We don't have any plan to implement TablePlus cloud at the moment, we don't want to store user data. If we store user data, we need to take care of security, rewrite terms of service, privacy, and many other legal tasks.

<img width="710" alt="icloud" src="https://user-images.githubusercontent.com/3654622/81412933-cf62a500-916e-11ea-9c97-11106dc1c870.png">

**Comment by maltsev** [comment]
@huyphams thanks for implementing that!

How do I migrate all existing data (connections, queries, etc) to cloud sync? When I set the sync locations all my existing connections get removed.

**Comment by jason-klein** [comment]
> How do I migrate all existing data (connections, queries, etc) to cloud sync? When I set the sync locations all my existing connections get removed.

I moved my local TablePlus data to an iCloud folder so that I could share settings with another Mac. Here are my notes in case they help @maltsev or anyone else looking for instructions, since this issue kept coming up when I tried to find instructions. All of my existing connections, queries, history, filter preferences, etc. became available on the other Mac.

1. I opened TablePlus preferences and configured the 3 Locations (Connections, Queries/History, Others) to point to these 3 corresponding new folders that I manually created in my iCloud drive.
Apps\TablePlus\Connections\
Apps\TablePlus\Queries and History\
Apps\TablePlus\Other Settings\

2. I copied the entire contents of each of the following folders from my local storage to the corresponding folders in iCloud storage:
/Users/_USERNAME_/Library/Application Support/com.tinyapp.TablePlus/Data/  to Apps\TablePlus\Connections\
/Users/_USERNAME_/Library/Application Support/com.tinyapp.TablePlus/Cache/ to Apps\TablePlus\Queries and History\
/Users/_USERNAME_/Library/Application Support/com.tinyapp.TablePlus/Temp/ to Apps\TablePlus\Other Settings\

For example, the file "/Users/_USERNAME_/Library/Application Support/com.tinyapp.TablePlus/Data/Connections.plist" was copied to "Apps\TablePlus\Connections\Connections.plist" in my iCloud storage.

In case it isn't obvious, substitute _USERNAME_ with your actual Mac username.

**Comment by simsimmal** [comment]
Thx for this handy solution
