### ISSUE TITLE
Field BLOB with image base64 encoded

### ISSUE THREAD

**Issue by ghost** [TablePlus/TablePlus#427]
Hi @huyphams,

Is possible add a feature to be able to see image saved on database ( blob field ) but encoded with base64 ?

Thanks

**Comment by huyphams** [comment]
Could you suggest me an application that can open the field with an image encoded in base64?

**Comment by l41lt0n** [comment]
@huyphams 

You can test using it:
https://codebeautify.org/base64-to-image-converter

Attached is a base64file
[base64.txt](https://github.com/TablePlus/TablePlus/files/2003484/base64.txt)

**Comment by huyphams** [comment]
I know how to do it in TablePlus, but you know, I want to detect it automatically.
Building a Quick Look that can change encoding text/image/encode is easy but the UX is not a good idea.
Currently, TablePlus can detect binary in PostgreSQL bytea field, and view the attachment in the Quick Look. TablePlus supports various data type: image, gif, pdf etc...

It's not that simple in BLOB, because it can be anything with any encoding.

**Comment by huyphams** [comment]
No, I mean, the information must be a standard. This looks like your customization. Imagine I have a thousand users with a hundred of customization, hmm.

**Comment by l41lt0n** [comment]
I am not even sure.

Can you tell me how is value to insert to SQLITE an image. are there a bytea?

Thanks

**Comment by huyphams** [comment]
It was supported on the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
