### ISSUE TITLE
Ability to view 'First X Rows' and 'Last X Rows' before opening a table

### ISSUE THREAD

**Issue by brian-crane** [TablePlus/TablePlus#43]
I have tables that are many millions entries in length.  Right now we only have the option to 'Open' table but this causes all million entries to show, slowing down my user experience.  

In PgAdmin4 they have the feature 'show first 100 rows,' which is ID ASC LIMIT 100 (see below).  Maybe have an option in preferences window to change value from 100 to  a custom value.  Adding the ability to view Filtered Rows is a nice feature but is a not a must-have.

![screen shot 2017-08-16 at 3 34 59 pm](https://user-images.githubusercontent.com/7946786/29388190-7db6e5a0-8298-11e7-8ca3-1f04d2d921de.png)

**Comment by brian-crane** [comment]
@huyphams,

any updates on this?  still unable to view large tables

**Comment by huyphams** [comment]
Hi @brian-crane we can change the limit number in paging section.
<img width="302" alt="screen shot 2017-10-24 at 12 44 15 am" src="https://user-images.githubusercontent.com/3654622/31904125-80d22e42-b854-11e7-8d6b-df36b654011b.png">

Because table not always have indexes, so I'm not sure how to implement the order without accident slow down all the queries.

**Comment by brian-crane** [comment]
@huyphams This solution does not work quite well enough - on large tables once I open to view, entire application will hang and I need to restart.  There should be a way to view the X most recent rows of a table _before_ we open the table, to avoid slowdown.

This is why I think the right click -> 'First X Rows' is the best way to go.  Currently we are forced to initially view _all_ rows of a table, and can only filter it after all items are loaded.  Like I said, with a table with 11M rows, this will crash TablePlus consistently.  This will be an issue for enterprise users

**Comment by huyphams** [comment]
Hi @brian-crane TablePlus doesn't load all rows when open table, if we have 602M rows in a table I think the bottle neck is: `select count(*) from tablename where condtion` we count rows for paging.

The best solution for now is using estimate instead of count(*). But sometime estimate return not exactly number of rows. [Read more about estimate](https://wiki.postgresql.org/wiki/Count_estimate)

I'm very happy to have a customer like you and you always give me a challenger to optimize TablePlus better and faster.

I will investigate on this issue and optimize it in next build 69.
- Huy

**Comment by huyphams** [comment]
A demo to show how to estimate work
<img width="1239" alt="screen_shot_2017-11-03_at_10_25_46_am" src="https://user-images.githubusercontent.com/3654622/32359593-b4fbc34c-c081-11e7-8611-0025d74d5892.png">

**Comment by huyphams** [comment]
Hi @brian-crane 

I have optimized for big table on new build: https://www.dropbox.com/s/3orqil53ktk8yzk/TablePlus.zip?dl=0

I tested on a table with a billion rows and it works fine.

Let me know if it fixes your issue.

**Comment by huyphams** [comment]
We have streaming row and estimate so this no not a problem anymore, so I going to close it 😄
