### ISSUE TITLE
Dark theme needs some fixing

### ISSUE THREAD

**Issue by msageryd** [TablePlus/TablePlus#466]
![image](https://user-images.githubusercontent.com/4483085/41460173-09decc82-708c-11e8-8906-22ecaeeca462.png)

The top "address"-row is barely readable in the dark theme

**Comment by huyphams** [comment]
You can change the title color by clicking on the title bar. The reason I keep the color when changing the color schema because some users choose their favorite color (Example: for production). If I changed it, that may cause some hazard because they can't recognize it is a production database.

<img width="1132" alt="screen shot 2018-06-15 at 4 09 11 pm" src="https://user-images.githubusercontent.com/3654622/41460297-74724ef0-70b6-11e8-8f16-408bb20c3a90.png">

**Comment by msageryd** [comment]
Thanks!
That's really great.
