### ISSUE TITLE
LIES! Don't put this on Github if you don't wanna give us the source!

### ISSUE THREAD

**Issue by soheil** [TablePlus/TablePlus#47]
Public shaming.

**Comment by brian-crane** [comment]
This GitHub is used for reporting Issues, providing a public Wiki, and Changelogs.

It would not make sense to reveal the source code of a commercial product.

**Comment by soheil** [comment]
You should release an open source version if you're gonna use github. You can still keep the licensed version separate and merge in any new pull requests from here. This way others can improve this and you stay true to the purpose and spirit of github, an open source community!

**Comment by brian-crane** [comment]
You are correct that your solution is more in-line with GitHub's spirit and community, however this is not my product.  I can see why @huyphams uses GitHub for issue tracking though.

**Comment by soheil** [comment]
Use a bug tracker, bugzilla, etc!

**Comment by huyphams** [comment]
Hi @soheil , I understood what you concern and I'm still thinking that I'm using github in the wrong way.
But, there are an open source of TablePlus: https://github.com/TablePlus/DummiesData and will be more open source of TablePlus will be published in the future.

personalize, I love open source and have many open source in my github profile.
Thanks for your feedback.

**Comment by huyphams** [comment]
FYI: There are many team like me, they created an organization and used one of repositories for tracking issues, wiki and project and an other repositories for open source. Somebody using for book and wiki only. You can search awesome-<programing language> on Google and see a lot of results.
All they, using Github in many different ways.

And one more thing, have you check Cocoapods and Mac Homebrew? Github engineer have put some limit because their repo slow down github infrastructure: https://github.com/cocoapods/cocoapods/issues/4989


<img width="1440" alt="screen shot 2017-08-18 at 11 00 43 am" src="https://user-images.githubusercontent.com/3654622/29443768-83def176-8404-11e7-82e3-6ac58e37885b.png">

**Comment by hieuhlc** [comment]
What's wrong with using GitHub for issue tracking? What's wrong with you @soheil ?
Huy has the right to choose whatever and whenever he pushes to public repo. Don't be so crazy about it.
