### ISSUE TITLE
Feature request : UI polish - Data cell spacing

### ISSUE THREAD

**Issue by windware** [TablePlus/TablePlus#515]
1. Which driver are you using and version of it : MySQL 8

2. Which TablePlus build number are you using : 113

I'm very close to switching over from Sequel Pro (for their lack of continued stable releases without MySQL 8 support anytime soon and will never get PostgreSQL or Windows support.) and while the functionality seems ok in TablePlus, it would allow me to switch if these few feature requests are implemented. (I'm posting multiple issues under 'UI polish' and I wish for #218 and #297 too.)

- I'd like to have a bit more spacing between cells. (It's not about increasing the 'Row height' but even with 'Row height' set to 1, I want more spaces, so the data is easier to read.

By default, Sequel Pro has good amount of spacing and also the columns are extended enough, so none of the numbers are truncated by default.

Sequel Pro

![sequelpro-spacing](https://user-images.githubusercontent.com/4352236/42235007-54788ea0-7f31-11e8-8461-e521c20caad0.png)

TablePlus

![tableplus-spacing](https://user-images.githubusercontent.com/4352236/42235008-54a06b46-7f31-11e8-8ddc-9e182cfcfd69.png)

This goes same for the structure page. While some are also truncated in Sequel Pro, it would be nice if names and values with predictable lengths are not truncated by default.

Sequel Pro
![sequel-pro-strcture](https://user-images.githubusercontent.com/4352236/42236289-7b997c16-7f35-11e8-95cb-d0c14bf38449.png)

TablePlus
![tableplus-strcture](https://user-images.githubusercontent.com/4352236/42236290-7bc6688e-7f35-11e8-9582-3edaa33b8a4a.png)

**Comment by huyphams** [comment]
Hi @windware thanks for the detailed feedback. I will surely improve it in the next update. We release an update weekly.

**Comment by fagai** [comment]
When is this improvement going to be?
EXPLAIN is hard to see.

**Comment by huyphams** [comment]
All the sizing issue is fixed in the upcoming build 2018, you can download the beta here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

- Auto-sizing now fits the content.
- Cached sizing, if you change the column size, position, TablePlus remembers it for the next time.
- Row, cell spacing. Now you can custom it in the preferences, along with font size and font family.

Thank you for the feedback.

@fagai it should be the other issue.

**Comment by windware** [comment]
Great looking! However, this may not be directly related to this issue, but the lower half of word 'EMPTY' and 'NULL' seems to be truncated when using non default fonts. It fits fine when I decrease the font size to 10 or change the font to the system default and it works with font size 14 as well. I'm on MacOS 10.13.

![Screen Shot 2019-04-20 at 3 47 28 PM](https://user-images.githubusercontent.com/4352236/56453890-bfb9c800-6383-11e9-85fa-ba8b44867bce.png)

The caching of column size is great, but when I double click the row divider to try to auto resize a column's width, it spreads it to a pretty wide width but perhaps you can take the longest width of a value shown in the current table and adjust to that width instead?

Also, a very minor issue but the displayed font does not change when I change the font family in the preference and I have to change the font size to reflect the change.

Thanks for making it better.

**Comment by huyphams** [comment]
Thank you for the feedback. May I ask you some questions?
1. but the lower half of word 'EMPTY' and 'NULL' seems to be truncated when using non-default fonts
=> Which font are you using? I want to try it out.
2. The caching of column size is great, but when I double click the row divider to try to auto resize a column's width
=> This is one of the known issues, I override that function because I don't want the app freeze when the user accidentally double click on a column which contains many many characters. I will optimize it when I've got a new solution.

**Comment by windware** [comment]
1. Sorry, I've edited the above post. Please try 'Arial'.

2. Thanks!

**Comment by huyphams** [comment]
I fixed the font issue, the cell value is rendered correctly now.
<img width="251" alt="Screen Shot 2019-04-20 at 4 07 36 PM" src="https://user-images.githubusercontent.com/3654622/56455276-8df63080-6386-11e9-8c5c-16af501d881a.png">
