### ISSUE TITLE
Feature Request: "Navigate" > "New Tab" will open new tab with same content as current one

### ISSUE THREAD

**Issue by donbeave** [TablePlus/TablePlus#577]
Guys, I know, probably I'm too annoying. ))

One more feature request, which I think can port from Postico UX.

If you open a new tab in TablePlus now it will open new empty tab without anything. It's quite useless because it's probably not what ppl want to see. I think more often use case is the duplicate current result or current sql query. So, my suggestion is copy idea how it was already implemented in Postico. Here are some screenshots:

1) **when table `contracts` was opened**:

![image](https://user-images.githubusercontent.com/139017/43393373-65e8d8a4-9429-11e8-9589-c63c1ab13402.png)

after click on `new tab` option it will copy the current query with all filters and show it:

![image](https://user-images.githubusercontent.com/139017/43393410-8f7c0786-9429-11e8-911a-73db79aaf111.png)

2) another example, **when sql query tab was opened with one executed query**:

![image](https://user-images.githubusercontent.com/139017/43393433-acdb106a-9429-11e8-9e20-8fe84c4e67de.png)

after click on `new tab` option it will open new SQL tab with no query:

![image](https://user-images.githubusercontent.com/139017/43393454-c80912c4-9429-11e8-81f3-7e3d4f9d93f4.png)

But I think probably for the first and second cases can copy query and insert into an editor, but not automatically execute it.

And this is how it's implemented in TablePlus now, what I think is not convienient:

<img width="1244" alt="xnip2018-07-30_18-34-05" src="https://user-images.githubusercontent.com/139017/43393642-6c67b9f6-942a-11e8-84f5-e4b80a1820e0.png">

**Comment by huyphams** [comment]
First of all, I have no problem with the user's requests, I always appreciate every single feedback. People spend there time to test and give their idea, it's wonderful. Without user feedback, we can't make it.
About your idea:
I'm aware of it but I'm still thinking. TablePlus and Postico are not the same, it handles connection in a different way.

- Postico opens a new connection when you open a new tab, it's good because of independent. but when you have to ssh or the connection was slow (remote connect). it takes some time to open a new tab.

- TablePlus reuses connection, that why it open new tab instantly.

Currently, TablePlus doesn't allow to open 1 item in different tabs, as I said, I'm still thinking about this UX.

**Comment by huyphams** [comment]
It's supported on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
We will release it on the next update (within 2 weeks).
Thanks.
