### ISSUE TITLE
Enhancement for more mouse in menubar

### ISSUE THREAD

**Issue by jasonhanneman** [TablePlus/TablePlus#634]
Hi, I noticed it is really hard to move the window around because the app completely fills all the draggable toolbar. My suggestion would be to move all the stuff in the window chrome toolbar to your own space below it so we can use the mouse to drag the window around. Move the stuff in the chrome down please. Thanks!
<img width="1443" alt="screen shot 2018-09-11 at 4 44 42 pm" src="https://user-images.githubusercontent.com/3942565/45389711-5cdca300-b5e2-11e8-9ea0-7a685b094a17.png">

**Comment by huyphams** [comment]
Hi @jasonhanneman @mattmacadams because you didn't fill the issue form so I'm not sure which build are you on. If you are on the latest build 125 you should be able to move the app around by click on anywhere on the title bar.
You can also custom title bar by right click on it, see the gif.
![2018-09-12 07 04 25](https://user-images.githubusercontent.com/3654622/45394301-1cb90700-b65a-11e8-84b1-794fd4a44498.gif)

**Comment by huyphams** [comment]
<img width="1217" alt="nice" src="https://user-images.githubusercontent.com/3654622/45394374-76b9cc80-b65a-11e8-9481-a28306295a19.png">

**Comment by alvint** [comment]
@huyphams Even though @jasonhanneman gave a screenshot for the main app, he may be talking about the initial connection screen. When you try to drag the window there you wind up dragging a connection group instead.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/622202/45423916-dae08e80-b662-11e8-8e2b-61653437aaf4.png">

**Comment by alvint** [comment]
@huyphams Even though @jasonhanneman gave a screenshot for the main app, he may be talking about the initial connection screen. When you try to drag the window there you wind up dragging a connection group instead.
