### ISSUE TITLE
why filters condition use "contains" default, why not "equal"?

### ISSUE THREAD

**Issue by bulletRush** [TablePlus/TablePlus#635]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
* MySQL5.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
* build 125

3. The steps to reproduce this issue:
* in most situation, we use "equal" to filter records, and in most situation, a "equal" condition will hit some index. so why TablePlus use "contains" default? should you change this to "equal"?

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I think the best solution is TablePlus remembers the last selection. so everyone can have their favorite default.

**Comment by bulletRush** [comment]
> I think the best solution is TablePlus remembers the last selection. so everyone can have their favorite default.

but i still want change default behavior to "equal", so i can use "equal" default when open a new table

**Comment by ruudk** [comment]
Please change the default to equals. Contains is slow on big databases. Most of the time I'm actually searching by primary key (id) and there I want to use equals.

It's also super annoying that the default of filter is always "raw sql" rather than just the first column of the table (primary key, id). 
<img width="287" alt="Screenshot 2019-06-19 at 11 30 58" src="https://user-images.githubusercontent.com/104180/59754128-c5e5fb00-9285-11e9-8904-94ab9109dd9c.png">

**Comment by huyphams** [comment]
FYI @ruudk I received about 3 emails per day when I changed the default Raw SQL to the first column with equal. 
Everybody has their favorite behavior, it's really hard to make it fit for all. I understand it and this is one of the known issues.

Adding a config option would solve it and it's already in our plan. Btw, you only select it once and all the filter which are added later are cloned from your previous filter, so it won't be Raw SQL or contains

**Comment by huyphams** [comment]
You will be able to set the default operator and also the default column in the next update!
<img width="942" alt="default" src="https://user-images.githubusercontent.com/3654622/64399291-3bb86200-d03e-11e9-9f6a-110a300bcf92.png">
