### ISSUE TITLE
Pretty print for jsonb fields

### ISSUE THREAD

**Issue by alvarolizama** [TablePlus/TablePlus#649]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

PostgreSQL 9.6.6

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

128

3. The steps to reproduce this issue:

Cant see a pretty print for jsonb fields 

![image 2018-09-18 at 11 35 25 am](https://user-images.githubusercontent.com/19955639/45702265-fce08200-bb36-11e8-84e1-388511304b2c.png)

Note: I have a Setapp version.

**Comment by huyphams** [comment]
Hi @alvarolizama thanks, meanwhile you can use the JSON Viewer in the quick look.
I think I will not change the format of the JSON field in the right panel because I want it to display the Raw value as it should be.
The only option I can add is the Raw field in the quick look, where you can pretty print or view it as JSON viewer.

**Comment by alvarolizama** [comment]
Oh that is perfect

**Comment by huyphams** [comment]
Hi @alvarolizama I miss understood, I just added a pretty option on detail row.
https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
