### ISSUE TITLE
Feature request: export multiple tables to sql file

### ISSUE THREAD

**Issue by m8rge** [TablePlus/TablePlus#656]
Please add ability to export multiple tables to single sql file.

**Comment by johndatserakis** [comment]
Yea this is a big one. Absolutely awesome app - but not sure how everyone's getting around not being able to highlight all your tables and export them all to one file. Maybe there's a work-around for that, but it's something I use with Sequel Pro every day.

**Comment by johndatserakis** [comment]
Ok so as I keep researching this - I think what we both want is the File -> Backup feature that already exists. There you can chose an entire database to backup - so that's a bit different but sorta the same thing.

The thing is - mine doesn't work because of this error: 

```
Dumping...
dump_pg_10.4: server version: 10.5 (Debian 10.5-1.pgdg90+1); dump_pg_10.4 version: 10.4
dump_pg_10.4: aborting because of server version mismatch

Dump database done
```

So what we'll need to see if that backup export can be done in sql - which would be good. I might be off here though.

**Comment by m8rge** [comment]
I found origin issue: https://github.com/TablePlus/TablePlus/issues/158

@johndatserakis please vote there.
