### ISSUE TITLE
Wrong count of rows in table

### ISSUE THREAD

**Issue by karol-pietrzak** [TablePlus/TablePlus#667]
1. MySQL 8.x and MySQL 5.x
server running 5.5.59-MariaDB

2. build 132

3. The steps to reproduce this issue:
* Created 300 000 records with script.
* IDs of rows shows also that there is 300 000 records. Table was turncated before.
* and this place shows taht there is 300,153 rows
![screen shot 2018-09-26 at 09 35 25](https://user-images.githubusercontent.com/43600181/46064385-86173a80-c16f-11e8-8b92-b12169be612f.png)

**Comment by huyphams** [comment]
it's not a bug, it's more like an UI issue and need to be improved.
By default, TablePlus estimates row instead of count exactly because of performance. 
You can increase this threshold if you want to count exactly row.
<img width="612" alt="estimate" src="https://user-images.githubusercontent.com/3654622/46064490-bb388280-c199-11e8-82dc-b66b230497b8.png">
From the new version, TablePlus will show it with a `~` to tell that it's an estimated number.

**Comment by karol-pietrzak** [comment]
all clear 
thanks!
