### ISSUE TITLE
Enhancement Request: Enable option to not include [ ] around Items

### ISSUE THREAD

**Issue by ngurney** [TablePlus/TablePlus#674]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): Microsoft SQL Server 2014

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 132

3. The steps to reproduce this issue:
Whenever you select a database item using autocomplete, it automatically wraps the item in brackets. 

It would be great to see an option in preferences to enable or disable this.

**Comment by huyphams** [comment]
TablePlus only add square brackets when the item name is Uppercase, mixed case (upper + lower case), containing spaces, or item has a name which is also a keyword.
The reason why we add the square brackets because we want to avoid the syntax error. But why you don't want to add brackets? is it your company conventions or copy to somewhere?

**Comment by farizzed** [comment]
I second this. This will be very neat because I usually copy my queries into my code. It is troublesome because, in my project, my teammates don't include the brackets for their queries inside the code. It makes the code easier to read. My workaround is when I need to copy my queries into my code. I have to delete the brackets wrapping the table name, but hey, that's another chore of my coding...

If I could suggest about the bracket adding, few SQL clients I know before using TablePlus, only encapsulates bracket the table name for specific syntax. For example, we write a table name **'type'** and we use autocomplete. The SQL client wraps the table **'type'** with brackets **[type]**. For other table names, the client doesn't need to wrap the bracket. This is just one example with bracket autocomplete.

**Comment by ngurney** [comment]
While I can defintely see value in adding it when there is a space or it is a SQL keyword there is no need for uppercase or mixed case items to be wrapped in brackets. 

Honestly it just doesn't fit our styling conventions, like @farizzed mentioned. It gives the impression that we are naming items with spaces or using SQL keywords which we avoid doing. We often name things in mixed case and when I glace at the code to me it looks like we are using all sorts of names we shouldn't because I see brackets everywhere. 

In any sense, the product is incredible and I will keep using it regardless of what you decide to do UX wise here.

**Comment by huyphams** [comment]
Of course, I will add an option or at least improve it, TablePlus should include the square bracket when it needed. (Ex: contains spaces).

**Comment by huyphams** [comment]
The brackets the mixed case are necessary.

For users who are using SQL Server with case-sensitive collation, you must include the [].

<img width="1160" alt="screen shot 2018-09-28 at 10 29 59 pm" src="https://user-images.githubusercontent.com/3654622/46218117-0f945b80-c36e-11e8-8419-f5c09661d238.png">

**Comment by ngurney** [comment]
@huyphams thanks for being willing to add it! I am still learning SQL and didn't know that some collations require brackets around mixed case items. 

Thanks again, and I hope you know that my entire SQL class at uni is super jealous of TablePlus while they are all stuck using Microsoft SQL Sever, so 👍

**Comment by huyphams** [comment]
Hi @ngurney @farizzed 
I added some enhancements on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
- No need to add brackets in case sensitive.
- 4 digits for money data type.
- Change the timestamp format.

We will release an update on Monday (this build can self-update) so it would be great if you guys can give it a try and let me know if there's any issue left.

**Comment by ngurney** [comment]
@huyphams sorry I am just seeing this now. Just tested production version and it is working perfect! Thanks so much, consider me a lifetime user of your product. I'll also suggest it to my team 👍🏼
