### ISSUE TITLE
When the table is many, the automatic completion is very slow

### ISSUE THREAD

**Issue by tianhao** [TablePlus/TablePlus#701]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
Oracle 12c
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 139
3. The steps to reproduce this issue:
My database has more than 100 users and more than 100,000 tables.
I finished typing "select" in 2 seconds, and the editor will display "select" after 20 seconds. I can't do anything with tableplus. Should optimize the auto-completion algorithm, or let me turn off auto-completion.

**Comment by tianhao** [comment]
Ok, I found it. 
Can TablePlus only complete the table of the current schema, not all users' tables

**Comment by huyphams** [comment]
hmm, it is not a full solution because many users are using that feature. They write a query which is crossing schemas.

**Comment by brianjsw** [comment]
In my case, I have a database with 300 tenants in it, each with the same set of 100 tables, for a total of 30,000 tables.  I would never care about the data in another schema because in this particular use case the objective was to segment the related data under a logical grouping (a schema).  I'm hoping TablePlus can find a way to implement a similar way of bounding the types of metadata operations it executes to within the context of a single schema.  This would greatly alleviate the performance problem.  I understand the issue because other users have the other use case where they DO run cross-schema queries.  I suppose it's probably going to come down to allowing the feature to be turned on or off on a case by case basis or allow the user to say "limit auto-complete to current schema".  Anyway looking forward to a fix and good luck with finding the best solution!

**Comment by huyphams** [comment]
The newest release should fix this issue! thank you!
