### ISSUE TITLE
[Feature Request] JSON viewer tool to work when the root of the JSON is an array

### ISSUE THREAD

**Issue by heathyboyj** [TablePlus/TablePlus#780]
See title - we get some client data as arrays rather than objects, and it's a shame not being able to use the same tool for everything!

**Comment by huyphams** [comment]
Because you didn't fill the form so I don't know which driver are you using. It should work if you're using PostgreSQL and the column type is JSON.

But if the field data type is text, TablePlus will try to parse it first. if it's a valid JSON, it will show with JSON viewer. I just added support for array type for this case.

**Comment by heathyboyj** [comment]
Sorry! I'm using MySQL 8.x. They are text fields (live DB is an old version of SQL that predates JSON columns, so not got around to making the conversion yet). This is what I see for arrays:

![screenshot 2018-11-06 at 09 36 28](https://user-images.githubusercontent.com/20686879/48055420-78f65e00-e1a7-11e8-8c0a-e8c6eee410dc.png)

But I was hoping it could be made to work like objects:

![screenshot 2018-11-06 at 09 36 07](https://user-images.githubusercontent.com/20686879/48055435-84e22000-e1a7-11e8-84b9-0d32fcfd6ae0.png)

Thanks!

**Comment by huyphams** [comment]
It's supported on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
It will be released in the next release (within a month).

**Comment by heathyboyj** [comment]
You rock, thanks!
