### ISSUE TITLE
Auto completion

### ISSUE THREAD

**Issue by huyphams** [TablePlus/TablePlus#82]
New feature in build 64
![autocompletion](https://user-images.githubusercontent.com/3654622/31162739-4e8fca02-a909-11e7-919e-e432c7af0c61.png)

**Comment by brian-crane** [comment]
How is auto-complete feature invoked?  I try typing "select * from schemaName.... then start typing table name but no auto complete window pops up.

By the way I love the new History and Favorite Query tabs - These will be very useful and my coworkers are already asking where to get TablePlus because they are jealous!

**Comment by huyphams** [comment]
@brian-crane auto-complete is on first phase and I need more feedback to make it better.
Next phase will come with auto complete column name, function template and of course table in schema.
