### ISSUE TITLE
It is not possible to create database view through TablePlus on PostgreSQL

### ISSUE THREAD

**Issue by deepj** [TablePlus/TablePlus#823]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
  PostgreSQL 10.5
2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
  156
3. The steps to reproduce this issue:

1. Tables -> New -> View
2. Write a query like `SELECT * FROM users`
3. Save it

![screenshot 2018-11-29 at 10 45 12](https://user-images.githubusercontent.com/33736/49213389-1bc38600-f3bc-11e8-8ab3-c75c3f705e48.png)

I'm a bit confused here. The view is created originally as `untitled_view_230`. A name `users_view` for the view is ignored. And the error is for `untitled_view_229`.

**Comment by huyphams** [comment]
it only happens when you commit by press `Command + S`. The text field `Name` only apply the change when hitting enter or leave focus. 

- Workaround: After changing the name to users_view, hit return or leave the text field before pressing Cmd + S.
- Solution: TablePlus should end editing of the `Name field` before committing the change.

**Comment by deepj** [comment]
@huyphams hm, it didn't help if you tried to do above. But after closing TablePlus and returning back it was possible then. Weird
