### ISSUE TITLE
how to edit in-line from a result of query ?

### ISSUE THREAD

**Issue by nobita96** [TablePlus/TablePlus#826]
how to edit in-line from a result of query ?

**Comment by huyphams** [comment]
Please fill the issue question, TablePlus supports many databases so I can support without that information.
Thanks.

**Comment by nobita96** [comment]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MariaDB 10.3.9

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Built 160

3. The steps to reproduce this issue:
 -> execute any SELECT query
 -> edit/ delete in-line any row from result of query
 -> press Enter or Command + S after edit: records not changes.

**Comment by alvint** [comment]
@troycurtisjr: It's complicated but I think doable, but it may be more work than it's worth. You'd need to reliably parse the original SQL to its various components (this alone is no small task, but you may be a tiny part of the way there depending on how syntax highlighting works), then auto-generate the update code based on the parsed components. Since most every type of database has a different syntax for updating with a join you'd have to come up with some sort of template system and replace the variables with the parsed parts.

I don't know if this is true, but it wouldn't surprise me if some of the more robust DB drivers did this for you, and that would far and away be the easiest way to support it. But that may be wishful thinking.

**Comment by huyphams** [comment]
It was fixed recently, thanks, everybody.

**Comment by alvint** [comment]
@huyphams Just out of curiosity, do the drivers support this or do you have to do it manually?

**Comment by huyphams** [comment]
Thing is simple @alvint 
1. Some of drivers support return the table name of the column in the result, so if all the columns are belong to one table, we can assume it was a simple select query (actually 90% of the times)
2. If the driver doesn’t support, I have to do it manually and use hueristic to guess the table name.
3. If user try to edit a result which came from many tables, TablePlus will warn users that it can’t be done, and in this case, users are okie with it (because they know it is impossible).

**Comment by alvint** [comment]
Ah! That's much easier than what I was thinking!
