### ISSUE TITLE
Connection is lost on SSH after 2 or 3 minutes of no usage

### ISSUE THREAD

**Issue by CyrilMazur** [TablePlus/TablePlus#895]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL 5.7

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

Build 176

3. The steps to reproduce this issue:

Connect to my remote database over SSH. Do nothing for 2 or 3 minutes. Then try to execute a query or manipulate a row, and it says the connection is lost, and it reconnects automatically (takes several seconds). The bug is systematic, connection is always lost after 2 or 3 minutes. "Keep connection alive" is enabled.

<img width="1280" alt="screenshot 2019-01-17 at 20 54 48" src="https://user-images.githubusercontent.com/464216/51320385-95155600-1a9a-11e9-83fa-c9f62ad6adbb.png">

**Comment by msageryd** [comment]
You could try to set up a separate SSH tunnel to ensure that the problem is with the tunnel within and not with your database connection.

I'm using several applications connected to my databases via SSH. Since not all apps has built in support for SSH tunnels I'm using an external app for tunnels. You could set up the tunnel at command line, but I prefer **Core Tunnel** for this. https://coretunnel.app/

**Comment by CyrilMazur** [comment]
@msageryd thanks. Actually the issue disappeared after I restarted Tableplus oO
