### ISSUE TITLE
Feature Request: Add a new connection from a user-generated connection config file

### ISSUE THREAD

**Issue by JiaboHou** [TablePlus/TablePlus#914]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.x

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
build 182

3. The steps to reproduce this issue:
n/a

I'd like to be able to write my own connection file that, when opened with TablePlus, can be used to connect to a DB. 

My use case for this is I have a bash command that automatically generates a DB password, which is time sensitive. So instead of changing the config in the app, have that same command generate a connection file that then gets opened by TablePlus.

**Comment by huyphams** [comment]
Hi @JiaboHou sorry because of the late response. You can open TablePlus from the terminal with the syntax:
`open "<url>"`
You can Copy As URL a connection from welcome screen to see the URL syntax but basically, it looks like this:
`postgresql://postgres@127.0.0.1/meme?statusColor=007F3D&enviroment=local&name=katonice%20copy&tLSMode=0&usePrivateKey=false`

**Comment by JiaboHou** [comment]
That almost works! I think the only issue now is that I'm running into #845 while trying to connect.

> sorry because of the late response

No worries at all!

**Comment by huyphams** [comment]
Hi @JiaboHou this one should work.
1. Open the file at  `~/Library/Application\ Support/com.tinyapp.TablePlus/Data/ConnectionGroups.plist`
You will see the list of connection but only contains basic info (No credentials because it is stored in the keychain).
2. Pick you connection ID.
3. Open Terminal: `open tableplus://?id=003723AF-1A22-449A-8833-3D51933B5FB9` then it should work.

**Comment by JiaboHou** [comment]
Hmm, I'm having permissions issues editing the file. Even `chmod` didn't help. I appreciate the suggestion but I think I'll wait for #845 to be resolved as the `open <url>` would be very suitable for my use case
