### ISSUE TITLE
Provide a "Script as" option in object context menu

### ISSUE THREAD

**Issue by jtwolgamott** [TablePlus/TablePlus#977]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostreSQL 10.0

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81): 194

Please consider adding a "Script as" option to the database object context ("Open in new tab", "Open structure", "Overview items", etc.) options. It would be great to have "Script as create", "Script as delete", "Script as insert", etc. as appropriate based on the object type selected. Selecting these options should generate the related script in a new query tab.

Thank you!

**Comment by huyphams** [comment]
Hi @jtwolgamott please download this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

After that, please download this plugin: 
[tabledump_plugin.zip](https://github.com/TablePlus/TablePlus/files/2882766/tabledump_plugin.zip)

Unzip and then double click to install the plugin, you will have scrip as in the menu context. I will publish this plugin after build 196 release because it contains some new APIs.

**Comment by jtwolgamott** [comment]
This is great Huy! Thank you so much for your prompt response!
