### ISSUE TITLE
Remove Count(*) SQL from console in Cassandra

### ISSUE THREAD

**Issue by yuanjun-jason** [TablePlus/TablePlus#997]
Cassandra 3.11.3

TablePlus build 190

Sometimes the loading data / filtering data is significantly slower than CQLSH.
The console shows 
SELECT COUNT(*) as count FROM "keyspace"."table"

But this is a known slow query and against CQL patterns. The Cassandra client should avoid this query whenever possible.

**Comment by huyphams** [comment]
Thanks @yuanjun-jason

**Comment by MightyPixel** [comment]
I have similar issue on large tables. Even if set beforehand the limit to 1 it still gets the total count. It should be an option whether it should display exact size, estimate size, "more than N" or off all together. My build is 2.3 (225).

**Comment by huyphams** [comment]
Hey guys, I've updated the Cassandra, TablePlus will try to estimate it before doing the count(*), so no more count if the table has more than 1 million rows.
Thank you for reminding me.

**Comment by huyphams** [comment]
And here is the build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0

**Comment by MightyPixel** [comment]
Hi @huyphams! Thanks for that update. I tested it and it indeed is better, but I my experience that it is way slower than cqlsh.

1. I had to wait for some reason something like 10 seconds before the loading bar disappears. Then Estimation of ~802,295 rows displayed.

1. 


2. 
3. It seems that other operations wait the estimation. So if I set the limit to 100, it loads 100 records and starts estimating and then if I change the limit to 200 it is delayed until the estimation finishes.

Is it possible to get a build with a setting to turn off the estimation/counting completely in order to verify if this is the root cause?

Kind Regards,
Ognyan

**Comment by huyphams** [comment]
Thank you @MightyPixel for the feedback, I will look into it now.

**Comment by yuanjun-jason** [comment]
Normally Cassandra users are aware of that COUNT(*) should not be used most of the time, so disabling this function when browsing data will not hurt.

**Comment by huyphams** [comment]
I turn off it completely: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
TablePlus only counts when you turn off the estimated count (default is on).
Let me know if anyone is still seeing it.

**Comment by MightyPixel** [comment]
Thanks @huyphams! I just tried it and it works very well - very responsive.

One cosmetic side-effect is that the label on the bottom: "1 of 0 row selected" could be "1 row selected"

Cheers!

**Comment by huyphams** [comment]
I fixed it @MightyPixel thank you 👍
